export const PLACES_DEMO = [
    {
        id: 0,
        name: "Donner",
        type: "Bookstore",
        latitude: 51.918852498892,
        longitude: 4.479435816744115,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Coolsingel 119, 3012 AG Rotterdam",
        tags: ["books", "culture", "reading"],
        languages: ["EN", "NL", "Other"],
        description: "Donner is one of the largest bookstores in the Netherlands, offering a wide range of books in multiple languages and hosting regular cultural events.",
        opening_times: {
            monday_open: "09:00",
            monday_close: "18:00",
            tuesday_open: "09:00",
            tuesday_close: "18:00",
            wednesday_open: "09:00",
            wednesday_close: "18:00",
            thursday_open: "09:00",
            thursday_close: "21:00",
            friday_open: "09:00",
            friday_close: "18:00",
            saturday_open: "09:00",
            saturday_close: "17:00",
            sunday_open: "12:00",
            sunday_close: "17:00"
        },
        logo: require("@/assets/images/placesdemo/donner-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=Donner+Rotterdam"
    },
    {
        id: 1,
        name: "Erasmus Esports",
        type: "Student Sport Association",
        latitude: 51.91008440463913,
        longitude: 4.509421634628058,
        city: "Rotterdam",
        district: "Feijenoord",
        address: "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        tags: ["gaming", "student", "community"],
        languages: ["EN", "NL", "Other"],
        description: "Erasmus Esports is a student-run organization at Erasmus University Rotterdam, offering a community for gamers to connect, compete, and collaborate through various events and tournaments.",
        opening_times: {
            monday_open: null,
            monday_close: null,
            tuesday_open: "19:00",
            tuesday_close: "23:00",
            wednesday_open: "19:00",
            wednesday_close: "23:00",
            thursday_open: null,
            thursday_close: null,
            friday_open: "19:00",
            friday_close: "23:00",
            saturday_open: null,
            saturday_close: null,
            sunday_open: null,
            sunday_close: null
        },
        logo: require("@/assets/images/placesdemo/erasmusesports-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=Erasmus+Esports+Rotterdam"
    },
    {
        id: 2,
        name: "Skateland",
        type: "Sports",
        latitude: 51.90793221738516,
        longitude: 4.5120429426214494,
        city: "Rotterdam",
        district: "Feijenoord",
        address: "Piekstraat 45, 3071 EL Rotterdam",
        tags: ["skateboarding", "BMX", "indoor park"],
        languages: ["NL", "EN", "Other"],
        description: "Skateland is one of the largest indoor skateparks in the Netherlands, offering facilities for skateboarding, BMX, and inline skating, along with lessons and events for all ages.",
        opening_times: {
            monday_open: null,
            monday_close: null,
            tuesday_open: null,
            tuesday_close: null,
            wednesday_open: "15:00",
            wednesday_close: "22:00",
            thursday_open: "15:00",
            thursday_close: "22:00",
            friday_open: "15:00",
            friday_close: "22:00",
            saturday_open: "13:00",
            saturday_close: "18:00",
            sunday_open: "13:00",
            sunday_close: "18:00"
        },
        logo: require("@/assets/images/placesdemo/skateland-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=Skateland+Rotterdam"
    },
    {
        id: 3,
        name: "Rotown",
        type: "Concert Venue / Music Bar",
        latitude: 51.91689793565822,
        longitude: 4.471683329939567,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Nieuwe Binnenweg 19, 3014 GB Rotterdam",
        tags: ["live music", "bar", "restaurant"],
        languages: ["NL", "EN", "Other"],
        description: "Rotown is a renowned music venue and café in Rotterdam, hosting a variety of live performances ranging from indie bands to international artists, complemented by a cozy bar and restaurant.",
        opening_times: {
            monday_open: "12:00",
            monday_close: "04:00",
            tuesday_open: "12:00",
            tuesday_close: "04:00",
            wednesday_open: "12:00",
            wednesday_close: "04:00",
            thursday_open: "12:00",
            thursday_close: "04:00",
            friday_open: "11:00",
            friday_close: "04:00",
            saturday_open: "11:00",
            saturday_close: "04:00",
            sunday_open: "11:00",
            sunday_close: "04:00"
        },
        logo: require("@/assets/images/placesdemo/rotown-favicon.jpg"),
        google_maps_link: "https://maps.google.com/?q=Rotown+Rotterdam"
    },
    {
        id: 4,
        name: "Bar3",
        type: "Music Bar",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Nieuwe Binnenweg 17, 3014 GB Rotterdam",
        tags: ["alternative", "music", "bar"],
        languages: ["NL", "EN", "Other"],
        description: "Bar3 is an alternative music bar in Rotterdam, known for its eclectic music selection, vibrant atmosphere, and a variety of live performances and DJ sets.",
        opening_times: {
            monday_open: "19:00",
            monday_close: "03:00",
            tuesday_open: "19:00",
            tuesday_close: "03:00",
            wednesday_open: "19:00",
            wednesday_close: "03:00",
            thursday_open: "19:00",
            thursday_close: "03:00",
            friday_open: "19:00",
            friday_close: "04:00",
            saturday_open: "19:00",
            saturday_close: "04:00",
            sunday_open: "19:00",
            sunday_close: "03:00"
        },
        logo: require("@/assets/images/placesdemo/bar3-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=Bar3+Rotterdam"
    },
    {
        id: 5,
        name: "160K",
        type: "Arcade Hall / Bar",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Schiekade 201, 3013 BR Rotterdam",
        tags: ["arcade", "retro games", "bar"],
        languages: ["NL", "EN", "Other"],
        description: "160K is a retro arcade hall and bar in Rotterdam, offering a nostalgic gaming experience with classic arcade machines, complemented by a selection of drinks and snacks.",
        opening_times: {
            monday_open: null,
            monday_close: null,
            tuesday_open: null,
            tuesday_close: null,
            wednesday_open: "17:00",
            wednesday_close: "00:00",
            thursday_open: "17:00",
            thursday_close: "01:00",
            friday_open: "17:00",
            friday_close: "02:00",
            saturday_open: "16:00",
            saturday_close: "02:00",
            sunday_open: null,
            sunday_close: null
        },
        logo: require("@/assets/images/placesdemo/160k-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=160K+Rotterdam"
    },
    {
        id: 6,
        name: "Kino",
        type: "Cinema",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Gouvernestraat 129-133, 3014 PM Rotterdam",
        tags: ["cinema", "film", "culture"],
        languages: ["NL", "EN", "Other"],
        description: "Kino is a cinema, restaurant, and creative workspace in the heart of Rotterdam, offering a diverse range of films from arthouse to blockbusters.",
        opening_times: {
            monday_open: "10:00",
            monday_close: "01:00",
            tuesday_open: "10:00",
            tuesday_close: "01:00",
            wednesday_open: "10:00",
            wednesday_close: "01:00",
            thursday_open: "10:00",
            thursday_close: "01:00",
            friday_open: "10:00",
            friday_close: "02:00",
            saturday_open: "10:00",
            saturday_close: "02:00",
            sunday_open: "10:00",
            sunday_close: "01:00"
        },
        logo: require("@/assets/images/placesdemo/kino-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=Kino+Rotterdam"
    },
    {
        id: 7,
        name: "Worm",
        type: "Art Center",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Boomgaardsstraat 71, 3012 XA Rotterdam",
        tags: ["art", "culture", "music"],
        languages: ["NL", "EN", "Other"],
        description: "WORM is a multidisciplinary cultural center in Rotterdam, hosting concerts, film screenings, exhibitions, and more.",
        opening_times: {
            monday_open: "12:00",
            monday_close: "01:00",
            tuesday_open: "12:00",
            tuesday_close: "01:00",
            wednesday_open: "12:00",
            wednesday_close: "01:00",
            thursday_open: "12:00",
            thursday_close: "01:00",
            friday_open: "12:00",
            friday_close: "02:00",
            saturday_open: "12:00",
            saturday_close: "02:00",
            sunday_open: "12:00",
            sunday_close: "01:00"
        },
        logo: require("@/assets/images/placesdemo/worm-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=WORM+Rotterdam"
    },
    {
        id: 8,
        name: "V2",
        type: "Art Center",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Eendrachtsstraat 10, 3012 XL Rotterdam",
        tags: ["art", "technology", "media"],
        languages: ["NL", "EN", "Other"],
        description: "V2_ is an interdisciplinary center for art and media technology, organizing exhibitions, presentations, and research projects.",
        opening_times: {
            monday_open: "10:00",
            monday_close: "18:00",
            tuesday_open: "10:00",
            tuesday_close: "18:00",
            wednesday_open: "10:00",
            wednesday_close: "18:00",
            thursday_open: "10:00",
            thursday_close: "18:00",
            friday_open: "10:00",
            friday_close: "18:00",
            saturday_open: "Closed",
            saturday_close: "Closed",
            sunday_open: "Closed",
            sunday_close: "Closed"
        },
        logo: require("@/assets/images/placesdemo/v2-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=V2+Rotterdam"
    },
    {
        id: 9,
        name: "Szeneviertel",
        type: "Bar",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Witte de Withstraat 63, 3012 BN Rotterdam",
        tags: ["bar", "drinks", "music"],
        languages: ["NL", "EN", "Other"],
        description: "Szeneviertel is a trendy bar located in the vibrant Witte de Withstraat, known for its eclectic music and lively atmosphere.",
        opening_times: {
            monday_open: "16:00",
            monday_close: "01:00",
            tuesday_open: "16:00",
            tuesday_close: "01:00",
            wednesday_open: "16:00",
            wednesday_close: "01:00",
            thursday_open: "16:00",
            thursday_close: "01:00",
            friday_open: "16:00",
            friday_close: "02:00",
            saturday_open: "16:00",
            saturday_close: "02:00",
            sunday_open: "16:00",
            sunday_close: "01:00"
        },
        logo: require("@/assets/images/placesdemo/szeneviertel-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=Szeneviertel+Rotterdam"
    },
    {
        id: 10,
        name: "Wunderbar",
        type: "Bar",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Boomgaardsstraat 71, 3012 XA Rotterdam",
        tags: ["bar", "alternative", "culture"],
        languages: ["NL", "EN", "Other"],
        description: "Wunderbar is an alternative bar located within WORM, offering a unique selection of drinks and a cozy atmosphere.",
        opening_times: {
            monday_open: "12:00",
            monday_close: "01:00",
            tuesday_open: "12:00",
            tuesday_close: "01:00",
            wednesday_open: "12:00",
            wednesday_close: "01:00",
            thursday_open: "12:00",
            thursday_close: "01:00",
            friday_open: "12:00",
            friday_close: "02:00",
            saturday_open: "12:00",
            saturday_close: "02:00",
            sunday_open: "12:00",
            sunday_close: "01:00"
        },
        logo: require("@/assets/images/placesdemo/v2-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=Wunderbar+Rotterdam"
    },
    {
        id: 11,
        name: "Hogeschool Rotterdam",
        type: "School",
        latitude: 51.91731349749627,
        longitude: 4.484378867887312,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Rochussenstraat 198, 3015 EK Rotterdam",
        tags: ["education", "university", "students"],
        languages: ["NL", "EN", "Other"],
        description: "Hogeschool Rotterdam is a university of applied sciences offering a wide range of bachelor's and master's programs.",
        opening_times: {
            monday_open: "07:30",
            monday_close: "19:00",
            tuesday_open: "07:30",
            tuesday_close: "20:00",
            wednesday_open: "07:30",
            wednesday_close: "19:00",
            thursday_open: "07:30",
            thursday_close: "19:00",
            friday_open: "07:30",
            friday_close: "18:00",
            saturday_open: "Closed",
            saturday_close: "Closed",
            sunday_open: "Closed",
            sunday_close: "Closed"
        },
        logo: require("@/assets/images/placesdemo/v2-favicon.png"),
        google_maps_link: "https://maps.google.com/?q=Hogeschool+Rotterdam"
    },
    {
        "id": 12,
        "name": "NN Douwe Egberts Café",
        "type": "Café",
        "latitude": 51.9237494,
        "longitude": 4.4712685,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Stationsplein 25, 3013 AJ Rotterdam",
        "tags": ["café", "coffee", "study", "laptop-friendly"],
        "languages": ["NL", "EN"],
        "description": "A modern café near Rotterdam Central Station offering a comfortable environment for coffee lovers and remote workers.",
        "opening_times": {
            "monday_open": "07:30",
            "monday_close": "18:00",
            "tuesday_open": "07:30",
            "tuesday_close": "18:00",
            "wednesday_open": "07:30",
            "wednesday_close": "18:00",
            "thursday_open": "07:30",
            "thursday_close": "18:00",
            "friday_open": "07:30",
            "friday_close": "18:00",
            "saturday_open": "08:30",
            "saturday_close": "18:00",
            "sunday_open": "08:30",
            "sunday_close": "18:00"
        },
        "logo": null,
        "google_maps_link": "https://maps.google.com/?q=NN+Douwe+Egberts+Café+Rotterdam"
    },
    {
        "id": 13,
        "name": "Heilige Boontjes",
        "type": "Café",
        "latitude": 51.916644,
        "longitude": 4.4701034,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Eendrachtsplein 3, 3015 LA Rotterdam",
        "tags": ["café", "social enterprise", "coffee", "breakfast"],
        "languages": ["NL", "EN"],
        "description": "A social enterprise café housed in a former police station, employing ex-inmates to help them reintegrate into society.",
        "opening_times": {
            "monday_open": "09:00",
            "monday_close": "18:00",
            "tuesday_open": "08:00",
            "tuesday_close": "18:00",
            "wednesday_open": "08:00",
            "wednesday_close": "18:00",
            "thursday_open": "08:00",
            "thursday_close": "18:00",
            "friday_open": "08:00",
            "friday_close": "18:00",
            "saturday_open": "10:00",
            "saturday_close": "18:00",
            "sunday_open": "10:00",
            "sunday_close": "18:00"
        },
        "logo": null,
        "google_maps_link": "https://maps.google.com/?q=Heilige+Boontjes+Rotterdam"
    },
    {
        "id": 14,
        "name": "BACKYARD",
        "type": "Café",
        "latitude": 51.9196432,
        "longitude": 4.47977693,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Korte Hoogstraat 14, 3011 GL Rotterdam",
        "tags": ["café", "plant-based", "vegan", "brunch"],
        "languages": ["NL", "EN"],
        "description": "An urban, green hangout offering a 100% plant-based menu in the heart of Rotterdam.",
        "opening_times": {
            "monday_open": "09:00",
            "monday_close": "18:00",
            "tuesday_open": "09:00",
            "tuesday_close": "18:00",
            "wednesday_open": "09:00",
            "wednesday_close": "21:00",
            "thursday_open": "09:00",
            "thursday_close": "21:00",
            "friday_open": "09:00",
            "friday_close": "21:00",
            "saturday_open": "09:00",
            "saturday_close": "21:00",
            "sunday_open": "09:00",
            "sunday_close": "21:00"
        },
        "logo": null,
        "google_maps_link": "https://maps.google.com/?q=Backyard+Rotterdam"
    },
    {
        "id": 15,
        "name": "Centrale Bibliotheek Rotterdam",
        "type": "Library",
        "latitude": 51.9210943,
        "longitude": 4.4866137,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Hoogstraat 110, 3011 PV Rotterdam",
        "tags": ["library", "study", "books", "public"],
        "languages": ["NL", "EN"],
        "description": "The central library of Rotterdam offering a vast collection of books, study spaces, and various cultural events.",
        "opening_times": {
            "monday_open": "13:00",
            "monday_close": "21:00",
            "tuesday_open": "10:00",
            "tuesday_close": "21:00",
            "wednesday_open": "10:00",
            "wednesday_close": "21:00",
            "thursday_open": "10:00",
            "thursday_close": "21:00",
            "friday_open": "10:00",
            "friday_close": "21:00",
            "saturday_open": "10:00",
            "saturday_close": "17:00",
            "sunday_open": "13:00",
            "sunday_close": "17:00"
        },
        "logo": null,
        "google_maps_link": "https://maps.google.com/?q=Centrale+Bibliotheek+Rotterdam"
    },
    {
        "id": 16,
        "name": "Biergarten",
        "type": "Bar",
        "latitude": 51.925423,
        "longitude": 4.4737291,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Schiestraat 18, 3013 AH Rotterdam",
        "tags": ["bar", "beer", "outdoor", "music"],
        "languages": ["NL", "EN"],
        "description": "An open-air bar offering a variety of beers, food, and live music events in a relaxed atmosphere.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "Closed",
            "tuesday_close": "Closed",
            "wednesday_open": "16:00",
            "wednesday_close": "23:30",
            "thursday_open": "16:00",
            "thursday_close": "23:30",
            "friday_open": "15:00",
            "friday_close": "01:00",
            "saturday_open": "12:00",
            "saturday_close": "01:00",
            "sunday_open": "12:00",
            "sunday_close": "00:00"
        },
        "logo": null,
        "google_maps_link": "https://maps.google.com/?q=Biergarten+Rotterdam"
    },
    {
        "id": 17,
        "name": "Kaapse Brouwers",
        "type": "Bar",
        "latitude": 51.9044814,
        "longitude": 4.4012009,
        "city": "Rotterdam",
        "district": "Katendrecht",
        "address": "Veerlaan 19D, 3072 AN Rotterdam",
        "tags": ["bar", "brewery", "craft beer", "waterfront"],
        "languages": ["NL", "EN"],
        "description": "A craft beer bar with over 24 taps, offering a waterfront view and a rotating selection of seasonal brews.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "12:00",
            "tuesday_close": "23:00",
            "wednesday_open": "12:00",
            "wednesday_close": "23:00",
            "thursday_open": "12:00",
            "thursday_close": "23:00",
            "friday_open": "12:00",
            "friday_close": "23:00",
            "saturday_open": "12:00",
            "saturday_close": "23:00",
            "sunday_open": "12:00",
            "sunday_close": "23:00"
        },
        "logo": null,
        "google_maps_link": "https://maps.google.com/?q=Kaapse+Brouwers+Rotterdam"
    },
    {
        "id": 18,
        "name": "Beest Boulders",
        "type": "Bouldering",
        "latitude": 51.927392,
        "longitude": 4.4737071,
        "city": "Rotterdam",
        "district": "Noord",
        "address": "Benthemplein 10, 3032 CC Rotterdam",
        "tags": ["bouldering", "climbing", "fitness", "indoor sports"],
        "languages": ["NL", "EN"],
        "description": "Beest Boulders Rotterdam offers over 220 bouldering problems across four floors, catering to all skill levels. The facility includes a strength training area and a lounge with panoramic city views.",
        "opening_times": {
            "monday_open": "09:00",
            "monday_close": "23:00",
            "tuesday_open": "09:00",
            "tuesday_close": "23:00",
            "wednesday_open": "09:00",
            "wednesday_close": "23:00",
            "thursday_open": "09:00",
            "thursday_close": "23:00",
            "friday_open": "09:00",
            "friday_close": "23:00",
            "saturday_open": "09:00",
            "saturday_close": "23:00",
            "sunday_open": "09:00",
            "sunday_close": "23:00"
        },
        "logo": "require('@/assets/images/placesdemo/beestboulders.png')",
        "google_maps_link": "https://maps.google.com/?q=Beest+Boulders+Rotterdam"
    },
    {
        "id": 19,
        "name": "Queer Rotterdam",
        "type": "Queer Community Group",
        "latitude": 51.9143409,
        "longitude": 4.4400976,
        "city": "Rotterdam",
        "district": "Centrum",
        "address": "Various locations, Rotterdam",
        "tags": ["LGBTQ+", "community", "events", "support"],
        "languages": ["NL", "EN"],
        "description": "Queer Rotterdam is a volunteer-run collective organizing events and activities for the LGBTQI+ community, fostering connection and empowerment in an inclusive environment.",
        "opening_times": {
            "monday_open": "Varies",
            "monday_close": "Varies",
            "tuesday_open": "Varies",
            "tuesday_close": "Varies",
            "wednesday_open": "Varies",
            "wednesday_close": "Varies",
            "thursday_open": "Varies",
            "thursday_close": "Varies",
            "friday_open": "Varies",
            "friday_close": "Varies",
            "saturday_open": "Varies",
            "saturday_close": "Varies",
            "sunday_open": "Varies",
            "sunday_close": "Varies"
        },
        "logo": "require('@/assets/images/placesdemo/queerrotterdam.png')",
        "google_maps_link": "https://maps.google.com/?q=Queer+Rotterdam"
    },
    {
        "id": 20,
        "name": "Ferry",
        "type": "Queer Bar",
        "latitude": 51.9170151,
        "longitude": 4.4729362,
        "city": "Rotterdam",
        "district": "Centrum",
        "address": "Westblaak 127, 3012 KJ Rotterdam",
        "tags": ["bar", "LGBTQ+", "nightlife", "events"],
        "languages": ["NL", "EN"],
        "description": "Ferry is a vibrant queer bar and café offering a welcoming space with two floors and a terrace. It hosts regular events, including DJ nights and drag performances.",
        "opening_times": {
            "monday_open": "16:00",
            "monday_close": "00:00",
            "tuesday_open": "16:00",
            "tuesday_close": "00:00",
            "wednesday_open": "16:00",
            "wednesday_close": "00:00",
            "thursday_open": "16:00",
            "thursday_close": "01:00",
            "friday_open": "16:00",
            "friday_close": "02:30",
            "saturday_open": "14:00",
            "saturday_close": "02:30",
            "sunday_open": "14:00",
            "sunday_close": "22:00"
        },
        "logo": "require('@/assets/images/placesdemo/ferry.png')",
        "google_maps_link": "https://maps.google.com/?q=Ferry+Rotterdam"
    },
    {
        "id": 21,
        "name": "Cinerama",
        "type": "Cinema",
        "latitude": 51.9170756,
        "longitude": 4.4762712,
        "city": "Rotterdam",
        "district": "Centrum",
        "address": "Westblaak 18, 3012 KL Rotterdam",
        "tags": ["cinema", "arthouse", "films", "culture"],
        "languages": ["NL", "EN"],
        "description": "Cinerama is a historic cinema featuring seven screens and a mix of mainstream and arthouse films. It also hosts various film festivals throughout the year.",
        "opening_times": {
            "monday_open": "12:30",
            "monday_close": "00:00",
            "tuesday_open": "12:30",
            "tuesday_close": "00:00",
            "wednesday_open": "12:30",
            "wednesday_close": "00:00",
            "thursday_open": "12:30",
            "thursday_close": "00:00",
            "friday_open": "12:30",
            "friday_close": "00:00",
            "saturday_open": "12:30",
            "saturday_close": "00:00",
            "sunday_open": "12:30",
            "sunday_close": "00:00"
        },
        "logo": "require('@/assets/images/placesdemo/ferry.png')",
        "google_maps_link": "https://maps.google.com/?q=Cinerama+Rotterdam"
    },
      {
    "id": 22,
    "name": "De Slegte",
    "type": "Bookstore",
    "latitude": 51.9210891,
    "longitude": 4.4838334,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Hoogstraat 141, 3011 PM Rotterdam",
    "tags": ["bookstore", "secondhand", "study books", "literature"],
    "languages": ["NL", "EN"],
    "description": "De Slegte is a renowned bookstore in Rotterdam, offering a vast collection of secondhand books, study materials, and literary works. It's a haven for book enthusiasts seeking both classic and contemporary titles.",
    "opening_times": {
      "monday_open": "12:00",
      "monday_close": "18:00",
      "tuesday_open": "10:00",
      "tuesday_close": "18:00",
      "wednesday_open": "10:00",
      "wednesday_close": "18:00",
      "thursday_open": "10:00",
      "thursday_close": "18:00",
      "friday_open": "10:00",
      "friday_close": "21:00",
      "saturday_open": "10:00",
      "saturday_close": "18:00",
      "sunday_open": "12:00",
      "sunday_close": "17:00"
    },
    "logo": "require('@/assets/images/placesdemo/de-slegte.png')",
    "google_maps_link": "https://maps.google.com/?q=De+Slegte+Rotterdam"
  },
  {
    "id": 23,
    "name": "Toffler",
    "type": "Nightclub",
    "latitude": 51.9235959,
    "longitude": 4.4728292,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Weena-Zuid 33, 3012 NH Rotterdam",
    "tags": ["nightclub", "electronic music", "underground", "techno"],
    "languages": ["NL", "EN"],
    "description": "Toffler is an iconic underground nightclub located in a former metro tunnel beneath Weena. Known for its intimate atmosphere and cutting-edge electronic music, it's a staple in Rotterdam's nightlife scene.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "Closed",
      "tuesday_close": "Closed",
      "wednesday_open": "Closed",
      "wednesday_close": "Closed",
      "thursday_open": "Closed",
      "thursday_close": "Closed",
      "friday_open": "23:00",
      "friday_close": "06:00",
      "saturday_open": "23:00",
      "saturday_close": "06:00",
      "sunday_open": "Closed",
      "sunday_close": "Closed"
    },
    "logo": "require('@/assets/images/placesdemo/toffler.png')",
    "google_maps_link": "https://maps.google.com/?q=Toffler+Rotterdam"
  },
  {
    "id": 24,
    "name": "Annabel",
    "type": "Music Venue",
    "latitude": 51.9253806,
    "longitude": 4.4734658,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Schiestraat 20, 3013 AH Rotterdam",
    "tags": ["music venue", "concerts", "club nights", "live music"],
    "languages": ["NL", "EN"],
    "description": "Annabel is Rotterdam's largest pop venue, hosting a diverse range of concerts and club nights. Located near Central Station, it features a spacious terrace and a vibrant atmosphere for music enthusiasts.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "11:00",
      "tuesday_close": "05:00",
      "wednesday_open": "11:00",
      "wednesday_close": "05:00",
      "thursday_open": "11:00",
      "thursday_close": "04:00",
      "friday_open": "11:00",
      "friday_close": "04:00",
      "saturday_open": "17:00",
      "saturday_close": "04:00",
      "sunday_open": "Closed",
      "sunday_close": "Closed"
    },
    "logo": "require('@/assets/images/placesdemo/annabel.png')",
    "google_maps_link": "https://maps.google.com/?q=Annabel+Rotterdam"
  },
  {
    "id": 25,
    "name": "Teds op het dak",
    "type": "Café",
    "latitude": 51.9256766,
    "longitude": 4.4740312,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Schiekade 189, 3013 BR Rotterdam",
    "tags": ["café", "rooftop", "brunch", "panoramic views"],
    "languages": ["NL", "EN"],
    "description": "Teds op het dak is a charming rooftop café offering all-day brunch with stunning views of Rotterdam's skyline. Nestled atop the Schieblock building, it's a perfect spot for a relaxed meal in a lush setting.",
    "opening_times": {
      "monday_open": "10:00",
      "monday_close": "17:00",
      "tuesday_open": "10:00",
      "tuesday_close": "17:00",
      "wednesday_open": "10:00",
      "wednesday_close": "17:00",
      "thursday_open": "10:00",
      "thursday_close": "17:00",
      "friday_open": "10:00",
      "friday_close": "20:00",
      "saturday_open": "09:00",
      "saturday_close": "20:00",
      "sunday_open": "09:00",
      "sunday_close": "20:00"
    },
    "logo": "require('@/assets/images/placesdemo/teds.png')",
    "google_maps_link": "https://maps.google.com/?q=Teds+op+het+dak+Rotterdam"
  }, 
  {
    "id": 26,
    "name": "Perron",
    "type": "Nightclub",
    "latitude": 51.9254191,
    "longitude": 4.4721746,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Schiestraat 42, 3013 AH Rotterdam",
    "tags": ["nightlife", "techno", "underground"],
    "languages": ["NL", "EN"],
    "description": "Perron is a renowned nightclub in Rotterdam, celebrated for its electrifying techno beats and vibrant atmosphere, attracting both locals and tourists.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "Closed",
      "tuesday_close": "Closed",
      "wednesday_open": "Closed",
      "wednesday_close": "Closed",
      "thursday_open": "Closed",
      "thursday_close": "Closed",
      "friday_open": "23:59",
      "friday_close": "06:00",
      "saturday_open": "23:59",
      "saturday_close": "06:00",
      "sunday_open": "Closed",
      "sunday_close": "Closed"
    },
    "logo": "https://www.perron.nl/assets/images/logo.png",
    "google_maps_link": "https://maps.google.com/?q=Perron+Rotterdam"
  },
  {
    "id": 27,
    "name": "Roodkapje",
    "type": "Cultural Center",
    "latitude": 51.9248886,
    "longitude": 4.471909,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Delftseplein 39, 3013 AA Rotterdam",
    "tags": ["art", "music", "community"],
    "languages": ["NL", "EN"],
    "description": "Roodkapje is a vibrant cultural hub in Rotterdam, known for its eclectic blend of art, music, and creative experimentation, serving as a dynamic venue for emerging talent.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "12:00",
      "tuesday_close": "22:00",
      "wednesday_open": "12:00",
      "wednesday_close": "22:00",
      "thursday_open": "12:00",
      "thursday_close": "23:00",
      "friday_open": "12:00",
      "friday_close": "23:00",
      "saturday_open": "12:00",
      "saturday_close": "23:00",
      "sunday_open": "12:00",
      "sunday_close": "22:00"
    },
    "logo": "https://roodkapje.org/assets/images/logo.png",
    "google_maps_link": "https://maps.google.com/?q=Roodkapje+Rotterdam"
  },
  {
    "id": 28,
    "name": "Burgertrut",
    "type": "Restaurant",
    "latitude": 51.9248541,
    "longitude": 4.4720209,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Delftseplein 39, 3013 AA Rotterdam",
    "tags": ["restaurant", "vegan", "burgers"],
    "languages": ["NL", "EN"],
    "description": "Burgertrut is a cozy restaurant in Rotterdam offering a variety of homemade burgers, including vegan options, in a relaxed and artistic setting.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "12:00",
      "tuesday_close": "22:00",
      "wednesday_open": "12:00",
      "wednesday_close": "22:00",
      "thursday_open": "12:00",
      "thursday_close": "23:00",
      "friday_open": "12:00",
      "friday_close": "23:00",
      "saturday_open": "12:00",
      "saturday_close": "23:00",
      "sunday_open": "12:00",
      "sunday_close": "22:00"
    },
    "logo": "https://roodkapje.org/assets/images/logo.png",
    "google_maps_link": "https://maps.google.com/?q=Burgertrut+Rotterdam"
  },
  {
    "id": 29,
    "name": "Fenix Food Factory",
    "type": "Food Market",
    "latitude": 51.9020098,
    "longitude": 4.4842887,
    "city": "Rotterdam",
    "district": "Katendrecht",
    "address": "Nico Koomanskade 1025, 3072 LM Rotterdam",
    "tags": ["food market", "local produce", "craft beer"],
    "languages": ["NL", "EN"],
    "description": "Fenix Food Factory is a dynamic food market in Rotterdam, housed in a former warehouse, offering a variety of local produce, craft beers, and artisanal products.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "10:00",
      "tuesday_close": "22:00",
      "wednesday_open": "10:00",
      "wednesday_close": "22:00",
      "thursday_open": "10:00",
      "thursday_close": "22:00",
      "friday_open": "10:00",
      "friday_close": "22:00",
      "saturday_open": "09:30",
      "saturday_close": "22:00",
      "sunday_open": "09:30",
      "sunday_close": "21:00"
    },
    "logo": "https://www.fenixfoodfactory.nl/assets/images/logo.png",
    "google_maps_link": "https://maps.google.com/?q=Fenix+Food+Factory+Rotterdam"
  },
    {
    "id": 30,
    "name": "Kleine Walhalla",
    "type": "Theater",
    "latitude": 51.9015922,
    "longitude": 4.4826287,
    "city": "Rotterdam",
    "district": "Katendrecht",
    "address": "Sumatraweg 9-11, 3072 ZP Rotterdam",
    "tags": ["theater", "intimate", "local artists", "cultural venue", "performing arts", "community", "events", "live performances", "artistic", "cozy"],
    "languages": ["NL", "EN"],
    "description": "Kleine Walhalla is an intimate theater space in Rotterdam's Katendrecht district, hosting a variety of performances by both emerging and established artists.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "13:00",
      "tuesday_close": "16:00",
      "wednesday_open": "13:00",
      "wednesday_close": "16:00",
      "thursday_open": "13:00",
      "thursday_close": "16:00",
      "friday_open": "13:00",
      "friday_close": "16:00",
      "saturday_open": "Closed",
      "saturday_close": "Closed",
      "sunday_open": "Closed",
      "sunday_close": "Closed"
    },
    "logo": null,
    "google_maps_link": "https://maps.google.com/?q=Kleine+Walhalla+Rotterdam"
  },
  {
    "id": 31,
    "name": "Nieuwe Luxor Theater",
    "type": "Theater",
    "latitude": 51.907128,
    "longitude": 4.4883574,
    "city": "Rotterdam",
    "district": "Kop van Zuid",
    "address": "Posthumalaan 1, 3072 AG Rotterdam",
    "tags": ["theater", "modern", "large capacity", "musicals", "concerts", "dance", "opera", "cabaret", "international productions", "cultural hub"],
    "languages": ["NL", "EN"],
    "description": "Nieuwe Luxor Theater is a modern performing arts venue located at the foot of the Erasmus Bridge in Rotterdam, known for hosting a wide range of large-scale productions.",
    "opening_times": {
      "monday_open": "10:00",
      "monday_close": "18:00",
      "tuesday_open": "10:00",
      "tuesday_close": "18:00",
      "wednesday_open": "10:00",
      "wednesday_close": "18:00",
      "thursday_open": "10:00",
      "thursday_close": "18:00",
      "friday_open": "10:00",
      "friday_close": "18:00",
      "saturday_open": "12:00",
      "saturday_close": "18:00",
      "sunday_open": "12:00",
      "sunday_close": "18:00"
    },
    "logo": null,
    "google_maps_link": "https://maps.google.com/?q=Nieuwe+Luxor+Theater+Rotterdam"
  },
  {
    "id": 32,
    "name": "LantarenVenster",
    "type": "Cinema",
    "latitude": 51.9048318,
    "longitude": 4.4844183,
    "city": "Rotterdam",
    "district": "Kop van Zuid",
    "address": "Otto Reuchlinweg 996, 3072 MD Rotterdam",
    "tags": ["cinema", "jazz", "film screenings", "concerts", "festivals", "cultural events", "restaurant", "art house", "live music", "educational programs"],
    "languages": ["NL", "EN"],
    "description": "LantarenVenster is a cultural venue in Rotterdam offering a diverse program of films, jazz concerts, and festivals, along with a restaurant and educational activities.",
    "opening_times": {
      "monday_open": "11:30",
      "monday_close": "01:00",
      "tuesday_open": "11:30",
      "tuesday_close": "01:00",
      "wednesday_open": "11:30",
      "wednesday_close": "01:00",
      "thursday_open": "11:30",
      "thursday_close": "01:00",
      "friday_open": "11:30",
      "friday_close": "01:00",
      "saturday_open": "09:30",
      "saturday_close": "01:00",
      "sunday_open": "09:30",
      "sunday_close": "01:00"
    },
    "logo": null,
    "google_maps_link": "https://maps.google.com/?q=LantarenVenster+Rotterdam"
  },
  {
    "id": 33,
    "name": "Historische Tuin Schoonoord",
    "type": "Park",
    "latitude": 51.9086472,
    "longitude": 4.4701521,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Kievitslaan 8, 3016 CG Rotterdam",
    "tags": ["park", "historic garden", "greenery", "tranquil", "nature", "walking paths", "botanical", "relaxation", "scenic", "urban oasis"],
    "languages": ["NL", "EN"],
    "description": "Historische Tuin Schoonoord is a serene historic garden in the heart of Rotterdam, offering visitors a peaceful retreat amidst lush greenery and diverse plant species.",
    "opening_times": {
      "monday_open": "08:30",
      "monday_close": "16:30",
      "tuesday_open": "08:30",
      "tuesday_close": "16:30",
      "wednesday_open": "08:30",
      "wednesday_close": "16:30",
      "thursday_open": "08:30",
      "thursday_close": "16:30",
      "friday_open": "08:30",
      "friday_close": "16:30",
      "saturday_open": "08:30",
      "saturday_close": "16:30",
      "sunday_open": "08:30",
      "sunday_close": "16:30"
    },
    "logo": null,
    "google_maps_link": "https://maps.google.com/?q=Historische+Tuin+Schoonoord+Rotterdam"
  },
  {
    "id": 34,
    "name": "Mystiek",
    "type": "Store",
    "latitude": 51.9163654,
    "longitude": 4.4771888,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Schiedamse Vest 89B, 3012 BG Rotterdam",
    "tags": ["alternative", "metaphysical"],
    "languages": ["NL", "EN"],
    "description": " ",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "Closed",
      "tuesday_close": "Closed",
      "wednesday_open": "Closed",
      "wednesday_close": "Closed",
      "thursday_open": "22:00",
      "thursday_close": "04:00",
      "friday_open": "22:00",
      "friday_close": "05:00",
      "saturday_open": "22:00",
      "saturday_close": "05:00",
      "sunday_open": "Closed",
      "sunday_close": "Closed"
    },
    "logo": null,
    "google_maps_link": "https://maps.google.com/?q=Mystiek+Rotterdam"
  },
  {
    "id": 35,
    "name": "Boekhandel van Gennep",
    "type": "Bookstore",
    "latitude": 51.9172815,
    "longitude": 4.4709029,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Oude Binnenweg 131B, 3012 JD Rotterdam",
    "tags": ["bookstore", "literature", "poetry", "art books", "children's books", "photography", "cozy", "independent", "readings", "cultural"],
    "languages": ["NL", "EN"],
    "description": "Boekhandel van Gennep is a cozy independent bookstore in Rotterdam offering a curated selection of literature, poetry, art, and photography books, along with regular author readings.",
    "opening_times": {
      "monday_open": "12:00",
      "monday_close": "18:00",
      "tuesday_open": "10:00",
      "tuesday_close": "18:00",
      "wednesday_open": "10:00",
      "wednesday_close": "18:00",
      "thursday_open": "10:00",
      "thursday_close": "18:00",
      "friday_open": "10:00",
      "friday_close": "18:00",
      "saturday_open": "10:00",
      "saturday_close": "17:00",
      "sunday_open": "Closed",
      "sunday_close": "Closed"
    },
    "logo": null,
    "google_maps_link": "https://maps.google.com/?q=Boekhandel+van+Gennep+Rotterdam"
  },
    {
    "id": 36,
    "name": "Rejoes",
    "type": "Second Hand Clothing Store",
    "latitude": 51.9176524,
    "longitude": 4.4766628,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Oude Binnenweg 34, 3012 JE Rotterdam",
    "tags": ["second-hand", "vintage", "fashion", "sustainable", "affordable", "urban", "casual", "unisex", "trendy", "streetwear"],
    "languages": ["NL", "EN"],
    "description": "Rejoes is a popular second-hand fashion store offering a wide range of vintage clothing and accessories for both men and women.",
    "opening_times": {
      "monday_open": "11:00",
      "monday_close": "19:30",
      "tuesday_open": "10:00",
      "tuesday_close": "20:00",
      "wednesday_open": "10:00",
      "wednesday_close": "20:00",
      "thursday_open": "10:00",
      "thursday_close": "20:00",
      "friday_open": "10:00",
      "friday_close": "20:00",
      "saturday_open": "10:00",
      "saturday_close": "20:00",
      "sunday_open": "12:00",
      "sunday_close": "18:30"
    },
    "logo": "https://rejoes.com/",
    "google_maps_link": "https://maps.google.com/?q=Kilo+Kilo+store+Rotterdam"
  },
  {
    "id": 37,
    "name": "De Après Skihut",
    "type": "Bar",
    "latitude": 51.9223802,
    "longitude": 4.4741391,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Stadhuisplein 29, 3012 AR Rotterdam",
    "tags": ["bar", "party", "après-ski", "music", "dance", "nightlife", "drinks", "fun", "entertainment", "themed"],
    "languages": ["NL", "EN"],
    "description": "De Après Skihut is a vibrant après-ski themed bar offering lively music, dancing, and a festive atmosphere reminiscent of alpine parties.",
    "opening_times": {
      "monday_open": "10:00",
      "monday_close": "04:00",
      "tuesday_open": "10:00",
      "tuesday_close": "04:00",
      "wednesday_open": "10:00",
      "wednesday_close": "04:00",
      "thursday_open": "10:00",
      "thursday_close": "04:00",
      "friday_open": "10:00",
      "friday_close": "05:00",
      "saturday_open": "10:00",
      "saturday_close": "05:00",
      "sunday_open": "10:00",
      "sunday_close": "04:00"
    },
    "logo": "https://deapresskihut.nl/",
    "google_maps_link": "https://maps.google.com/?q=De+Après+Skihut+Rotterdam"
  },
  {
    "id": 38,
    "name": "De Gele Kanarie Cafe",
    "type": "Bar",
    "latitude": 51.9228109,
    "longitude": 4.4859978,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Goudsesingel 284, 3011 KH Rotterdam",
    "tags": ["bar", "cafe", "beer", "food", "lunch", "dinner", "craft beer", "cozy", "modern", "social"],
    "languages": ["NL", "EN"],
    "description": "De Gele Kanarie Cafe is a modern bar and cafe known for its own brewed beer, offering a cozy atmosphere for lunch, dinner, and drinks.",
    "opening_times": {
      "monday_open": "15:00",
      "monday_close": "01:00",
      "tuesday_open": "15:00",
      "tuesday_close": "01:00",
      "wednesday_open": "15:00",
      "wednesday_close": "01:00",
      "thursday_open": "15:00",
      "thursday_close": "01:00",
      "friday_open": "15:00",
      "friday_close": "01:00",
      "saturday_open": "12:00",
      "saturday_close": "01:00",
      "sunday_open": "12:00",
      "sunday_close": "23:00"
    },
    "logo": "https://www.degelekanarie.com/",
    "google_maps_link": "https://maps.google.com/?q=De+Gele+Kanarie+Cafe+Rotterdam"
  },
  {
    "id": 39,
    "name": "Deli Tasty",
    "type": "Restaurant",
    "latitude": 51.9233262,
    "longitude": 4.482632,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Meent 40, 3011 JL Rotterdam",
    "tags": ["restaurant", "Vietnamese", "Asian", "lunch", "dinner", "halal", "authentic", "cozy", "family-friendly", "affordable"],
    "languages": ["NL", "EN"],
    "description": "Deli Tasty is an authentic Vietnamese restaurant offering a variety of traditional dishes in a cozy and family-friendly setting.",
    "opening_times": {
      "monday_open": "12:00",
      "monday_close": "22:00",
      "tuesday_open": "12:00",
      "tuesday_close": "22:00",
      "wednesday_open": "12:00",
      "wednesday_close": "22:00",
      "thursday_open": "12:00",
      "thursday_close": "22:00",
      "friday_open": "12:00",
      "friday_close": "22:00",
      "saturday_open": "12:00",
      "saturday_close": "22:00",
      "sunday_open": "12:00",
      "sunday_close": "22:00"
    },
    "logo": "https://delitasty.nl/",
    "google_maps_link": "https://maps.google.com/?q=Deli+Tasty+Rotterdam"
  },
  {
    "id": 40,
    "name": "Cheap Fashion",
    "type": "Second Hand Clothing Store",
    "latitude": 51.9237678,
    "longitude": 4.4828559,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Meent 25, 3011 JB Rotterdam",
    "tags": ["second-hand", "vintage", "fashion", "affordable", "retro", "unique", "sustainable", "casual", "unisex", "eclectic"],
    "languages": ["NL", "EN"],
    "description": "Cheap Fashion is a well-known vintage store offering a diverse range of affordable second-hand clothing and accessories for all styles.",
    "opening_times": {
      "monday_open": "11:00",
      "monday_close": "18:00",
      "tuesday_open": "10:00",
      "tuesday_close": "18:00",
      "wednesday_open": "10:00",
      "wednesday_close": "18:00",
      "thursday_open": "10:00",
      "thursday_close": "18:00",
      "friday_open": "10:00",
      "friday_close": "18:00",
      "saturday_open": "10:00",
      "saturday_close": "18:00",
      "sunday_open": "12:00",
      "sunday_close": "17:00"
    },
    "logo": "https://rotterdam.info/locaties/cheap-fashion/",
    "google_maps_link": "https://maps.google.com/?q=Cheap+Fashion+Rotterdam"
  },
    {
    "id": 41,
    "name": "Pebbles Kitty Cat Café",
    "type": "Cat Café",
    "latitude": 51.9229726,
    "longitude": 4.4918148,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Hoogstraat 30A, 3011 PR Rotterdam",
    "tags": ["cat café", "coffee", "tea", "cats", "board games", "vegan options", "relaxing", "cozy", "pet-friendly", "desserts"],
    "languages": ["NL", "EN"],
    "description": "Pebbles Kitty Cat Café is Rotterdam's first and only cat café, offering a cozy environment where visitors can enjoy coffee, tea, and treats while interacting with resident cats.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "12:00",
      "tuesday_close": "17:00",
      "wednesday_open": "12:00",
      "wednesday_close": "17:00",
      "thursday_open": "12:00",
      "thursday_close": "17:00",
      "friday_open": "12:00",
      "friday_close": "17:00",
      "saturday_open": "10:30",
      "saturday_close": "17:00",
      "sunday_open": "10:30",
      "sunday_close": "17:00"
    },
    "logo": "require('@/assets/images/placesdemo/pebbles-kitty-cat-cafe.png')",
    "google_maps_link": "https://maps.google.com/?q=Pebbles+Kitty+Cat+Café+Rotterdam"
  },
  {
    "id": 42,
    "name": "The Social Hub Rotterdam",
    "type": "Hotel & Co-working Space",
    "latitude": 51.9212788,
    "longitude": 4.502891,
    "city": "Rotterdam",
    "district": "Kralingen-Crooswijk",
    "address": "Willem Ruyslaan 225, 3063 ER Rotterdam",
    "tags": ["hotel", "co-working", "student housing", "events", "restaurant", "gym", "community", "networking", "modern", "urban"],
    "languages": ["NL", "EN"],
    "description": "The Social Hub Rotterdam is a hybrid hospitality concept combining hotel accommodations, student housing, co-working spaces, and event venues, fostering a vibrant community for travelers, students, and professionals.",
    "opening_times": {
      "monday_open": "00:00",
      "monday_close": "23:59",
      "tuesday_open": "00:00",
      "tuesday_close": "23:59",
      "wednesday_open": "00:00",
      "wednesday_close": "23:59",
      "thursday_open": "00:00",
      "thursday_close": "23:59",
      "friday_open": "00:00",
      "friday_close": "23:59",
      "saturday_open": "00:00",
      "saturday_close": "23:59",
      "sunday_open": "00:00",
      "sunday_close": "23:59"
    },
    "logo": "require('@/assets/images/placesdemo/the-social-hub-rotterdam.png')",
    "google_maps_link": "https://maps.google.com/?q=The+Social+Hub+Rotterdam"
  },
  {
    "id": 43,
    "name": "Skate Fever",
    "type": "Sports",
    "latitude": 51.924714,
    "longitude": 4.5639559,
    "city": "Rotterdam",
    "district": "Feijenoord",
    "address": "Rhijnspoor 275, 2901 LB Capelle aan den IJssel",
    "tags": ["roller skating", "disco", "family fun", "music", "events", "birthday parties", "skate rental", "indoor", "sports", "entertainment"],
    "languages": ["NL", "EN"],
    "description": "Skate Fever is an indoor roller disco offering a vibrant atmosphere with music, lights, and skating fun for all ages, perfect for parties and events.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "Closed",
      "tuesday_close": "Closed",
      "wednesday_open": "14:00",
      "wednesday_close": "22:00",
      "thursday_open": "14:00",
      "thursday_close": "22:00",
      "friday_open": "14:00",
      "friday_close": "23:00",
      "saturday_open": "12:00",
      "saturday_close": "23:00",
      "sunday_open": "12:00",
      "sunday_close": "22:00"
    },
    "logo": "require('@/assets/images/placesdemo/skate-fever.png')",
    "google_maps_link": "https://maps.google.com/?q=Skate+Fever+Rotterdam"
  },
  {
    "id": 44,
    "name": "Hollywood Entertainment Center",
    "type": "Arcade & Bowling",
    "latitude": 51.8961215,
    "longitude": 4.522459,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Cor Kieboomplein 513, 3077 MK Rotterdam",
    "tags": ["arcade", "bowling", "escape rooms", "minigolf", "sports bar", "family entertainment", "VR games", "events", "dining", "leisure"],
    "languages": ["NL", "EN"],
    "description": "Hollywood Entertainment Center is a multifaceted leisure venue featuring arcade games, bowling alleys, escape rooms, minigolf, and dining options, catering to all age groups.",
    "opening_times": {
      "monday_open": "11:00",
      "monday_close": "23:00",
      "tuesday_open": "11:00",
      "tuesday_close": "23:00",
      "wednesday_open": "11:00",
      "wednesday_close": "23:00",
      "thursday_open": "11:00",
      "thursday_close": "23:00",
      "friday_open": "11:00",
      "friday_close": "01:00",
      "saturday_open": "11:00",
      "saturday_close": "01:00",
      "sunday_open": "11:00",
      "sunday_close": "23:00"
    },
    "logo": "require('@/assets/images/placesdemo/hollywood-entertainment-center.png')",
    "google_maps_link": "https://maps.google.com/?q=Hollywood+Entertainment+Center+Rotterdam"
  },
  {
    "id": 45,
    "name": "Gamestate de Kuip",
    "type": "Arcade",
    "latitude": 51.8968932,
    "longitude": 4.5222146,
    "city": "Rotterdam",
    "district": "Feijenoord",
    "address": "Cor Kieboomplein 109, 3077 MK Rotterdam",
    "tags": ["arcade", "gaming", "family fun", "ticket redemption", "modern games", "entertainment", "indoor", "fun zone", "video games", "leisure"],
    "languages": ["NL", "EN"],
    "description": "Gamestate de Kuip is a modern arcade offering a wide range of games for all ages, from classic machines to the latest gaming experiences.",
    "opening_times": {
      "monday_open": "12:00",
      "monday_close": "00:00",
      "tuesday_open": "12:00",
      "tuesday_close": "00:00",
      "wednesday_open": "12:00",
      "wednesday_close": "00:00",
      "thursday_open": "12:00",
      "thursday_close": "00:00",
      "friday_open": "12:00",
      "friday_close": "01:00",
      "saturday_open": "12:00",
      "saturday_close": "01:00",
      "sunday_open": "12:00",
      "sunday_close": "00:00"
    },
    "logo": "require('@/assets/images/placesdemo/gamestate-de-kuip.png')",
    "google_maps_link": "https://maps.google.com/?q=Gamestate+de+Kuip+Rotterdam"
  },
    {
    "id": 46,
    "name": "Pathé Schouwburgplein",
    "type": "Cinema",
    "latitude": 51.9207891,
    "longitude": 4.4708331,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Schouwburgplein 101, 3012 CL Rotterdam",
    "tags": ["cinema", "IMAX", "movies", "entertainment", "city center", "modern", "accessible", "film", "Rotterdam", "theater"],
    "languages": ["NL", "EN", "Other"],
    "description": "Pathé Schouwburgplein is a modern cinema located in the heart of Rotterdam, featuring 7 halls equipped with IMAX technology and luxurious seating. It's a popular destination for movie enthusiasts seeking the latest films in a comfortable setting.",
    "opening_times": {
      "monday_open": "10:00",
      "monday_close": "00:00",
      "tuesday_open": "10:00",
      "tuesday_close": "00:00",
      "wednesday_open": "10:00",
      "wednesday_close": "00:00",
      "thursday_open": "10:00",
      "thursday_close": "00:00",
      "friday_open": "10:00",
      "friday_close": "00:00",
      "saturday_open": "10:00",
      "saturday_close": "00:00",
      "sunday_open": "10:00",
      "sunday_close": "00:00"
    },
    "logo": "require('@/assets/images/placesdemo/pathe-schouwburgplein.png')",
    "google_maps_link": "https://maps.google.com/?q=Pathé+Schouwburgplein+Rotterdam"
  },
  {
    "id": 47,
    "name": "Baroeg",
    "type": "Music Venue",
    "latitude": 51.876749,
    "longitude": 4.5164991,
    "city": "Rotterdam",
    "district": "Lombardijen",
    "address": "Spinozaweg 300, 3076 ET Rotterdam",
    "tags": ["music", "venue", "alternative", "concerts", "subculture", "live music", "Rotterdam", "events", "nightlife", "bar"],
    "languages": ["NL", "EN", "Other"],
    "description": "Baroeg is a renowned music venue in Rotterdam, known for its focus on alternative and subcultural music genres. Hosting live concerts and events, it serves as a hub for music enthusiasts seeking unique performances.",
    "opening_times": {
      "monday_open": "18:00",
      "monday_close": "00:00",
      "tuesday_open": "18:00",
      "tuesday_close": "00:00",
      "wednesday_open": "18:00",
      "wednesday_close": "00:00",
      "thursday_open": "18:00",
      "thursday_close": "00:00",
      "friday_open": "18:00",
      "friday_close": "01:00",
      "saturday_open": "18:00",
      "saturday_close": "01:00",
      "sunday_open": "18:00",
      "sunday_close": "01:00"
    },
    "logo": "require('@/assets/images/placesdemo/baroeg.png')",
    "google_maps_link": "https://maps.google.com/?q=Baroeg+Rotterdam"
  },
  {
    "id": 48,
    "name": "Vessel 11",
    "type": "Music Venue & Restaurant",
    "latitude": 51.9172122,
    "longitude": 4.4834674,
    "city": "Rotterdam",
    "district": "Centrum",
    "address": "Wijnhaven 101, 3011 WN Rotterdam",
    "tags": ["music", "restaurant", "bar", "live music", "ship", "unique venue", "Rotterdam", "events", "dining", "entertainment"],
    "languages": ["NL", "EN", "Other"],
    "description": "Vessel 11 is a unique music venue and restaurant located on a red lightship in Rotterdam's Wijnhaven. Offering live music performances and a British-inspired menu, it provides a distinctive experience for visitors.",
    "opening_times": {
      "monday_open": "Closed",
      "monday_close": "Closed",
      "tuesday_open": "12:00",
      "tuesday_close": "00:00",
      "wednesday_open": "12:00",
      "wednesday_close": "00:00",
      "thursday_open": "12:00",
      "thursday_close": "00:00",
      "friday_open": "12:00",
      "friday_close": "01:00",
      "saturday_open": "11:00",
      "saturday_close": "01:00",
      "sunday_open": "11:00",
      "sunday_close": "00:00"
    },
    "logo": "require('@/assets/images/placesdemo/vessel11.png')",
    "google_maps_link": "https://maps.google.com/?q=Vessel+11+Rotterdam"
  },
  {
    "id": 49,
    "name": "Tuincentrum De Molen",
    "type": "Garden Center",
    "latitude": 51.883457,
    "longitude": 4.4667266,
    "city": "Rotterdam",
    "district": "Overschie",
    "address": "Kromme Zandweg 81, 3082 PZ Rotterdam",
    "tags": ["garden", "center", "plants", "flowers", "outdoor", "indoor", "Rotterdam", "gardening", "nursery", "greenery"],
    "languages": ["NL", "EN", "Other"],
    "description": "Tuincentrum De Molen is a comprehensive garden center in Rotterdam, offering a wide selection of plants, flowers, and gardening supplies. It's a go-to destination for gardening enthusiasts and professionals alike.",
    "opening_times": {
      "monday_open": "09:00",
      "monday_close": "17:00",
      "tuesday_open": "09:00",
      "tuesday_close": "17:00",
      "wednesday_open": "09:00",
      "wednesday_close": "17:00",
      "thursday_open": "09:00",
      "thursday_close": "17:00",
      "friday_open": "09:00",
      "friday_close": "17:00",
      "saturday_open": "09:00",
      "saturday_close": "17:00",
      "sunday_open": "12:00",
      "sunday_close": "17:00"
    },
    "logo": "require('@/assets/images/placesdemo/tuincentrum-de-molen.png')",
    "google_maps_link": "https://maps.google.com/?q=Tuincentrum+De+Molen+Rotterdam"
  }
];