export const PLACES_DEMO = [
    {
        id: 0,
        name: "Donner",
        type: "Bookstore",
        latitude: 51.918852498892,
        longitude: 4.479435816744115,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Coolsingel 119, 3012 AG Rotterdam",
        tags: ["books", "culture", "reading", "bookstore", "culture", "reading", "literature", "non-fiction", "fiction", "multilingual", "events", "study", "academic", "public"],
        languages: ["EN", "NL", "Other"],
        description: "Donner is one of the largest bookstores in the Netherlands, offering a wide range of books in multiple languages and hosting regular cultural events.",
        opening_times: {
            monday_open: "09:00",
            monday_close: "18:00",
            tuesday_open: "09:00",
            tuesday_close: "18:00",
            wednesday_open: "09:00",
            wednesday_close: "18:00",
            thursday_open: "09:00",
            thursday_close: "21:00",
            friday_open: "09:00",
            friday_close: "18:00",
            saturday_open: "09:00",
            saturday_close: "17:00",
            sunday_open: "12:00",
            sunday_close: "17:00"
        },
        logo: require("@/assets/images/placesdemo/donner-favicon.png"),
        "website": "https://www.donner.nl/en/",
        google_maps_link: "https://maps.google.com/?q=Donner+Rotterdam"
    },
    {
        id: 1,
        name: "Erasmus Esports",
        type: "Student Sport Association",
        latitude: 51.91008440463913,
        longitude: 4.509421634628058,
        city: "Rotterdam",
        district: "Feijenoord",
        address: "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        tags: ["gaming", "student", "community", "gaming", "esports", "students", "community", "competitive", "casual", "events", "social", "university", "technology"],
        languages: ["EN", "NL", "Other"],
        description: "Erasmus Esports is a student-run organization at Erasmus University Rotterdam, offering a community for gamers to connect, compete, and collaborate through various events and tournaments.",
        opening_times: {
            monday_open: null,
            monday_close: null,
            tuesday_open: "19:00",
            tuesday_close: "23:00",
            wednesday_open: "19:00",
            wednesday_close: "23:00",
            thursday_open: null,
            thursday_close: null,
            friday_open: "19:00",
            friday_close: "23:00",
            saturday_open: null,
            saturday_close: null,
            sunday_open: null,
            sunday_close: null
        },
        logo: require("@/assets/images/placesdemo/erasmusesports-favicon.png"),
        "website": "https://www.erasmusesports.nl/",
        google_maps_link: "https://maps.google.com/?q=Erasmus+Esports+Rotterdam"
    },
    {
        id: 2,
        name: "Skateland",
        type: "Sports",
        latitude: 51.90793221738516,
        longitude: 4.5120429426214494,
        city: "Rotterdam",
        district: "Feijenoord",
        address: "Piekstraat 45, 3071 EL Rotterdam",
        tags: ["skateboarding", "BMX", "indoor park", "skateboarding", "BMX", "inline skating", "indoor park", "sports", "youth", "lessons", "events", "community", "urban culture"],
        languages: ["NL", "EN", "Other"],
        description: "Skateland is one of the largest indoor skateparks in the Netherlands, offering facilities for skateboarding, BMX, and inline skating, along with lessons and events for all ages.",
        opening_times: {
            monday_open: null,
            monday_close: null,
            tuesday_open: null,
            tuesday_close: null,
            wednesday_open: "15:00",
            wednesday_close: "22:00",
            thursday_open: "15:00",
            thursday_close: "22:00",
            friday_open: "15:00",
            friday_close: "22:00",
            saturday_open: "13:00",
            saturday_close: "18:00",
            sunday_open: "13:00",
            sunday_close: "18:00"
        },
        logo: require("@/assets/images/placesdemo/skateland-favicon.png"),
        "website": "https://skateland.nl/",
        google_maps_link: "https://maps.google.com/?q=Skateland+Rotterdam"
    },
    {
        id: 3,
        name: "Rotown",
        type: "Concert Venue / Music Bar",
        latitude: 51.91689793565822,
        longitude: 4.471683329939567,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Nieuwe Binnenweg 19, 3014 GB Rotterdam",
        tags: ["live music", "bar", "restaurant", "live music", "bar", "restaurant", "concert venue", "indie", "alternative", "dining", "nightlife", "culture", "events"],
        languages: ["NL", "EN", "Other"],
        description: "Rotown is a renowned music venue and café in Rotterdam, hosting a variety of live performances ranging from indie bands to international artists, complemented by a cozy bar and restaurant.",
        opening_times: {
            monday_open: "12:00",
            monday_close: "04:00",
            tuesday_open: "12:00",
            tuesday_close: "04:00",
            wednesday_open: "12:00",
            wednesday_close: "04:00",
            thursday_open: "12:00",
            thursday_close: "04:00",
            friday_open: "11:00",
            friday_close: "04:00",
            saturday_open: "11:00",
            saturday_close: "04:00",
            sunday_open: "11:00",
            sunday_close: "04:00"
        },
        logo: require("@/assets/images/placesdemo/rotown-favicon.jpg"),
        "website": "https://www.rotown.nl/",
        google_maps_link: "https://maps.google.com/?q=Rotown+Rotterdam"
    },
    {
        id: 4,
        name: "Bar3",
        type: "Music Bar",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Nieuwe Binnenweg 17, 3014 GB Rotterdam",
        tags: ["alternative", "music", "bar", "alternative", "music", "bar", "rock", "metal", "DJ sets", "nightlife", "youth", "casual", "events"],
        languages: ["NL", "EN", "Other"],
        description: "Bar3 is an alternative music bar in Rotterdam, known for its eclectic music selection, vibrant atmosphere, and a variety of live performances and DJ sets.",
        opening_times: {
            monday_open: "19:00",
            monday_close: "03:00",
            tuesday_open: "19:00",
            tuesday_close: "03:00",
            wednesday_open: "19:00",
            wednesday_close: "03:00",
            thursday_open: "19:00",
            thursday_close: "03:00",
            friday_open: "19:00",
            friday_close: "04:00",
            saturday_open: "19:00",
            saturday_close: "04:00",
            sunday_open: "19:00",
            sunday_close: "03:00"
        },
        logo: require("@/assets/images/placesdemo/bar3-favicon.png"),
        "website": "https://bar3.nl/",
        google_maps_link: "https://maps.google.com/?q=Bar3+Rotterdam"
    },
    {
        id: 5,
        name: "160K",
        type: "Arcade Hall / Bar",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Schiekade 201, 3013 BR Rotterdam",
        tags: ["arcade", "retro games", "bar", "arcade", "retro games", "bar", "gaming", "nostalgia", "drinks", "social", "nightlife", "events", "youth"],
        languages: ["NL", "EN", "Other"],
        description: "160K is a retro arcade hall and bar in Rotterdam, offering a nostalgic gaming experience with classic arcade machines, complemented by a selection of drinks and snacks.",
        opening_times: {
            monday_open: null,
            monday_close: null,
            tuesday_open: null,
            tuesday_close: null,
            wednesday_open: "17:00",
            wednesday_close: "00:00",
            thursday_open: "17:00",
            thursday_close: "01:00",
            friday_open: "17:00",
            friday_close: "02:00",
            saturday_open: "16:00",
            saturday_close: "02:00",
            sunday_open: null,
            sunday_close: null
        },
        logo: require("@/assets/images/placesdemo/160k-favicon.png"),
        "website": "https://www.160k.nl/",
        google_maps_link: "https://maps.google.com/?q=160K+Rotterdam"
    },
    {
        id: 6,
        name: "Kino",
        type: "Cinema",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Gouvernestraat 129-133, 3014 PM Rotterdam",
        tags: ["cinema", "film", "culture", "cinema", "film", "culture", "arthouse", "blockbusters", "restaurant", "bar", "creative workspace", "events", "public"],
        languages: ["NL", "EN", "Other"],
        description: "Kino is a cinema, restaurant, and creative workspace in the heart of Rotterdam, offering a diverse range of films from arthouse to blockbusters.",
        opening_times: {
            monday_open: "10:00",
            monday_close: "01:00",
            tuesday_open: "10:00",
            tuesday_close: "01:00",
            wednesday_open: "10:00",
            wednesday_close: "01:00",
            thursday_open: "10:00",
            thursday_close: "01:00",
            friday_open: "10:00",
            friday_close: "02:00",
            saturday_open: "10:00",
            saturday_close: "02:00",
            sunday_open: "10:00",
            sunday_close: "01:00"
        },
        logo: require("@/assets/images/placesdemo/kino-favicon.png"),
        "website": "https://kinorotterdam.nl/",
        google_maps_link: "https://maps.google.com/?q=Kino+Rotterdam"
    },
    {
        id: 7,
        name: "Worm",
        type: "Art Center",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Boomgaardsstraat 71, 3012 XA Rotterdam",
        tags: ["art", "culture", "music", "art", "culture", "music", "experimental", "film", "exhibitions", "events", "alternative", "community", "creative"],
        languages: ["NL", "EN", "Other"],
        description: "WORM is a multidisciplinary cultural center in Rotterdam, hosting concerts, film screenings, exhibitions, and more.",
        opening_times: {
            monday_open: "12:00",
            monday_close: "01:00",
            tuesday_open: "12:00",
            tuesday_close: "01:00",
            wednesday_open: "12:00",
            wednesday_close: "01:00",
            thursday_open: "12:00",
            thursday_close: "01:00",
            friday_open: "12:00",
            friday_close: "02:00",
            saturday_open: "12:00",
            saturday_close: "02:00",
            sunday_open: "12:00",
            sunday_close: "01:00"
        },
        logo: require("@/assets/images/placesdemo/worm-favicon.png"),
        "website": "https://worm.org/",
        google_maps_link: "https://maps.google.com/?q=WORM+Rotterdam"
    },
    {
        id: 8,
        name: "V2",
        type: "Art Center",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Eendrachtsstraat 10, 3012 XL Rotterdam",
        tags: ["art", "technology", "media", "art", "technology", "media", "interdisciplinary", "exhibitions", "research", "innovation", "culture", "events", "creative"],
        languages: ["NL", "EN", "Other"],
        description: "V2_ is an interdisciplinary center for art and media technology, organizing exhibitions, presentations, and research projects.",
        opening_times: {
            monday_open: "10:00",
            monday_close: "18:00",
            tuesday_open: "10:00",
            tuesday_close: "18:00",
            wednesday_open: "10:00",
            wednesday_close: "18:00",
            thursday_open: "10:00",
            thursday_close: "18:00",
            friday_open: "10:00",
            friday_close: "18:00",
            saturday_open: "Closed",
            saturday_close: "Closed",
            sunday_open: "Closed",
            sunday_close: "Closed"
        },
        logo: require("@/assets/images/placesdemo/v2-favicon.png"),
        "website": "https://v2.nl/",
        google_maps_link: "https://maps.google.com/?q=V2+Rotterdam"
    },
    {
        id: 9,
        name: "Szeneviertel",
        type: "Bar",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Witte de Withstraat 63, 3012 BN Rotterdam",
        tags: ["bar", "drinks", "music", "bar", "drinks", "music", "trendy", "nightlife", "casual", "social", "youth", "culture", "events"],
        languages: ["NL", "EN", "Other"],
        description: "Szeneviertel is a trendy bar located in the vibrant Witte de Withstraat, known for its eclectic music and lively atmosphere.",
        opening_times: {
            monday_open: "16:00",
            monday_close: "01:00",
            tuesday_open: "16:00",
            tuesday_close: "01:00",
            wednesday_open: "16:00",
            wednesday_close: "01:00",
            thursday_open: "16:00",
            thursday_close: "01:00",
            friday_open: "16:00",
            friday_close: "02:00",
            saturday_open: "16:00",
            saturday_close: "02:00",
            sunday_open: "16:00",
            sunday_close: "01:00"
        },
        logo: require("@/assets/images/placesdemo/szeneviertel-favicon.png"),
        "website": "https://maps.google.com/?q=Szeneviertel+Rotterdam",
        google_maps_link: "https://maps.google.com/?q=Szeneviertel+Rotterdam"
    },
    {
        id: 10,
        name: "Wunderbar",
        type: "Bar",
        latitude: 51.92045667961497,
        longitude: 4.4755949619232185,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Boomgaardsstraat 71, 3012 XA Rotterdam",
        tags: ["bar", "alternative", "culture", "bar", "alternative", "culture", "drinks", "casual", "social", "events", "art", "music", "community"],
        languages: ["NL", "EN", "Other"],
        description: "Wunderbar is an alternative bar located within WORM, offering a unique selection of drinks and a cozy atmosphere.",
        opening_times: {
            monday_open: "12:00",
            monday_close: "01:00",
            tuesday_open: "12:00",
            tuesday_close: "01:00",
            wednesday_open: "12:00",
            wednesday_close: "01:00",
            thursday_open: "12:00",
            thursday_close: "01:00",
            friday_open: "12:00",
            friday_close: "02:00",
            saturday_open: "12:00",
            saturday_close: "02:00",
            sunday_open: "12:00",
            sunday_close: "01:00"
        },
        logo: require("@/assets/images/placesdemo/v2-favicon.png"),
        "website": "https://worm.org/spaces/wunderbar/",
        google_maps_link: "https://maps.google.com/?q=Wunderbar+Rotterdam"
    },
    {
        id: 11,
        name: "Hogeschool Rotterdam",
        type: "School",
        latitude: 51.91731349749627,
        longitude: 4.484378867887312,
        city: "Rotterdam",
        district: "Stadscentrum",
        address: "Rochussenstraat 198, 3015 EK Rotterdam",
        tags: ["study spot", "education", "university", "students", "education", "university", "students", "academic", "research", "public", "community", "innovation", "technology", "culture"],
        languages: ["NL", "EN", "Other"],
        description: "Hogeschool Rotterdam is a university of applied sciences offering a wide range of bachelor's and master's programs.",
        opening_times: {
            monday_open: "07:30",
            monday_close: "19:00",
            tuesday_open: "07:30",
            tuesday_close: "20:00",
            wednesday_open: "07:30",
            wednesday_close: "19:00",
            thursday_open: "07:30",
            thursday_close: "19:00",
            friday_open: "07:30",
            friday_close: "18:00",
            saturday_open: "Closed",
            saturday_close: "Closed",
            sunday_open: "Closed",
            sunday_close: "Closed"
        },
        logo: require("@/assets/images/placesdemo/v2-favicon.png"),
        "website": "https://www.hogeschoolrotterdam.nl/",
        google_maps_link: "https://maps.google.com/?q=Hogeschool+Rotterdam"
    },
    {
        "id": 12,
        "name": "NN Douwe Egberts Café",
        "type": "Café",
        "latitude": 51.9237494,
        "longitude": 4.4712685,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Stationsplein 25, 3013 AJ Rotterdam",
        "tags": ["study spot", "café", "coffee", "study", "laptop-friendly", "café", "coffee", "study", "laptop-friendly", "casual", "social", "drinks", "public", "relaxing", "work-friendly"],
        "languages": ["NL", "EN"],
        "description": "A modern café near Rotterdam Central Station offering a comfortable environment for coffee lovers and remote workers.",
        "opening_times": {
            "monday_open": "07:30",
            "monday_close": "18:00",
            "tuesday_open": "07:30",
            "tuesday_close": "18:00",
            "wednesday_open": "07:30",
            "wednesday_close": "18:00",
            "thursday_open": "07:30",
            "thursday_close": "18:00",
            "friday_open": "07:30",
            "friday_close": "18:00",
            "saturday_open": "08:30",
            "saturday_close": "18:00",
            "sunday_open": "08:30",
            "sunday_close": "18:00"
        },
        "logo": null,
        "website": "https://decafes.nl/",
        "google_maps_link": "https://maps.google.com/?q=NN+Douwe+Egberts+Café+Rotterdam"
    },
    {
        "id": 13,
        "name": "Heilige Boontjes",
        "type": "Café",
        "latitude": 51.916644,
        "longitude": 4.4701034,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Eendrachtsplein 3, 3015 LA Rotterdam",
        "tags": ["study spot", "café", "social enterprise", "coffee", "breakfast", "café", "social enterprise", "coffee", "breakfast", "community", "casual", "drinks", "public", "culture", "social impact"],
        "languages": ["NL", "EN"],
        "description": "A social enterprise café housed in a former police station, employing ex-inmates to help them reintegrate into society.",
        "opening_times": {
            "monday_open": "09:00",
            "monday_close": "18:00",
            "tuesday_open": "08:00",
            "tuesday_close": "18:00",
            "wednesday_open": "08:00",
            "wednesday_close": "18:00",
            "thursday_open": "08:00",
            "thursday_close": "18:00",
            "friday_open": "08:00",
            "friday_close": "18:00",
            "saturday_open": "10:00",
            "saturday_close": "18:00",
            "sunday_open": "10:00",
            "sunday_close": "18:00"
        },
        "logo": null,
        "website": "https://www.heiligeboontjes.com/",
        "google_maps_link": "https://maps.google.com/?q=Heilige+Boontjes+Rotterdam"
    },
    {
        "id": 14,
        "name": "BACKYARD",
        "type": "Café",
        "latitude": 51.9196432,
        "longitude": 4.47977693,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Korte Hoogstraat 14, 3011 GL Rotterdam",
        "tags": ["study spot", "café", "plant-based", "vegan", "brunch", "café", "plant-based", "vegan", "brunch", "casual", "social", "drinks", "public", "culture", "healthy"],
        "languages": ["NL", "EN"],
        "description": "An urban, green hangout offering a 100% plant-based menu in the heart of Rotterdam.",
        "opening_times": {
            "monday_open": "09:00",
            "monday_close": "18:00",
            "tuesday_open": "09:00",
            "tuesday_close": "18:00",
            "wednesday_open": "09:00",
            "wednesday_close": "21:00",
            "thursday_open": "09:00",
            "thursday_close": "21:00",
            "friday_open": "09:00",
            "friday_close": "21:00",
            "saturday_open": "09:00",
            "saturday_close": "21:00",
            "sunday_open": "09:00",
            "sunday_close": "21:00"
        },
        "logo": null,
        "website": "https://www.backyardrotterdam.nl/",
        "google_maps_link": "https://maps.google.com/?q=Backyard+Rotterdam"
    },
    {
        "id": 15,
        "name": "Centrale Bibliotheek Rotterdam",
        "type": "Library",
        "latitude": 51.9210943,
        "longitude": 4.4866137,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Hoogstraat 110, 3011 PV Rotterdam",
        "tags": ["study spot", "library", "study", "books", "public", "library", "study", "books", "public", "culture", "reading", "events", "community", "academic", "multilingual"],
        "languages": ["NL", "EN"],
        "description": "The central library of Rotterdam offering a vast collection of books, study spaces, and various cultural events.",
        "opening_times": {
            "monday_open": "13:00",
            "monday_close": "21:00",
            "tuesday_open": "10:00",
            "tuesday_close": "21:00",
            "wednesday_open": "10:00",
            "wednesday_close": "21:00",
            "thursday_open": "10:00",
            "thursday_close": "21:00",
            "friday_open": "10:00",
            "friday_close": "21:00",
            "saturday_open": "10:00",
            "saturday_close": "17:00",
            "sunday_open": "13:00",
            "sunday_close": "17:00"
        },
        "logo": null,
        "website": "https://www.bibliotheek.rotterdam.nl/",
        "google_maps_link": "https://maps.google.com/?q=Centrale+Bibliotheek+Rotterdam"
    },
    {
        "id": 16,
        "name": "Biergarten",
        "type": "Bar",
        "latitude": 51.925423,
        "longitude": 4.4737291,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Schiestraat 18, 3013 AH Rotterdam",
        "tags": ["bar", "beer", "outdoor", "music", "bar", "beer", "outdoor", "music", "casual", "social", "nightlife", "events", "food", "youth"],
        "languages": ["NL", "EN"],
        "description": "An open-air bar offering a variety of beers, food, and live music events in a relaxed atmosphere.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "Closed",
            "tuesday_close": "Closed",
            "wednesday_open": "16:00",
            "wednesday_close": "23:30",
            "thursday_open": "16:00",
            "thursday_close": "23:30",
            "friday_open": "15:00",
            "friday_close": "01:00",
            "saturday_open": "12:00",
            "saturday_close": "01:00",
            "sunday_open": "12:00",
            "sunday_close": "00:00"
        },
        "logo": null,
        "website": "https://biergartenrotterdam.nl/",
        "google_maps_link": "https://maps.google.com/?q=Biergarten+Rotterdam"
    },
    {
        "id": 17,
        "name": "Kaapse Brouwers",
        "type": "Bar",
        "latitude": 51.9044814,
        "longitude": 4.4012009,
        "city": "Rotterdam",
        "district": "Katendrecht",
        "address": "Veerlaan 19D, 3072 AN Rotterdam",
        "tags": ["bar", "brewery", "craft beer", "waterfront", "craft beer",
            "brewery",
            "waterfront",
            "casual",
            "local produce",
            "beer tasting",
            "food hall",
            "social",
            "independent",
            "beer garden",
            "hipster",
            "daytime",
            "group-friendly",
            "Fenix Food Factory",
            "Katendrecht"],
        "languages": ["NL", "EN"],
        "description": "A craft beer bar with over 24 taps, offering a waterfront view and a rotating selection of seasonal brews.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "12:00",
            "tuesday_close": "23:00",
            "wednesday_open": "12:00",
            "wednesday_close": "23:00",
            "thursday_open": "12:00",
            "thursday_close": "23:00",
            "friday_open": "12:00",
            "friday_close": "23:00",
            "saturday_open": "12:00",
            "saturday_close": "23:00",
            "sunday_open": "12:00",
            "sunday_close": "23:00"
        },
        "logo": null,
        "website": "https://kaapsebrouwers.nl/",
        "google_maps_link": "https://maps.google.com/?q=Kaapse+Brouwers+Rotterdam"
    },
    {
        "id": 18,
        "name": "Beest Boulders",
        "type": "Bouldering",
        "latitude": 51.927392,
        "longitude": 4.4737071,
        "city": "Rotterdam",
        "district": "Noord",
        "address": "Benthemplein 10, 3032 CC Rotterdam",
        "tags": ["bouldering", "climbing", "fitness", "indoor sports", "bouldering",
            "climbing gym",
            "fitness",
            "indoor sports",
            "training",
            "urban view",
            "multi-level",
            "community",
            "youth-friendly",
            "active lifestyle",
            "courses",
            "events",
            "Noord",
            "modern facility",
            "recreational"],
        "languages": ["NL", "EN"],
        "description": "Beest Boulders Rotterdam offers over 220 bouldering problems across four floors, catering to all skill levels. The facility includes a strength training area and a lounge with panoramic city views.",
        "opening_times": {
            "monday_open": "09:00",
            "monday_close": "23:00",
            "tuesday_open": "09:00",
            "tuesday_close": "23:00",
            "wednesday_open": "09:00",
            "wednesday_close": "23:00",
            "thursday_open": "09:00",
            "thursday_close": "23:00",
            "friday_open": "09:00",
            "friday_close": "23:00",
            "saturday_open": "09:00",
            "saturday_close": "23:00",
            "sunday_open": "09:00",
            "sunday_close": "23:00"
        },
        "logo": "require('@/assets/images/placesdemo/beestboulders.png')",
        "website": "https://beestboulders.nl/rotterdam/",
        "google_maps_link": "https://maps.google.com/?q=Beest+Boulders+Rotterdam"
    },
    {
        "id": 19,
        "name": "Queer Rotterdam",
        "type": "Queer Community Group",
        "latitude": 51.929956,
        "longitude": 4.4774825,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Teilingerstraat 120, Rotterdam",
        "tags": ["LGBTQ+", "community", "events", "support", "queer", "LGBTQ+",
            "community group",
            "inclusive",
            "supportive",
            "events",
            "volunteer-run",
            "adult-focused",
            "safe space",
            "empowerment",
            "social gatherings",
            "networking",
            "activism",
            "diverse"],
        "languages": ["NL", "EN"],
        "description": "Queer Rotterdam is a volunteer-run collective organizing events and activities for the LGBTQI+ community, fostering connection and empowerment in an inclusive environment.",
        "opening_times": {
            "monday_open": "Varies",
            "monday_close": "Varies",
            "tuesday_open": "Varies",
            "tuesday_close": "Varies",
            "wednesday_open": "Varies",
            "wednesday_close": "Varies",
            "thursday_open": "Varies",
            "thursday_close": "Varies",
            "friday_open": "Varies",
            "friday_close": "Varies",
            "saturday_open": "Varies",
            "saturday_close": "Varies",
            "sunday_open": "Varies",
            "sunday_close": "Varies"
        },
        "logo": "require('@/assets/images/placesdemo/queerrotterdam.png')",
        "website": "https://queerrotterdam.nl/",
        "google_maps_link": "https://maps.google.com/?q=Queer+Rotterdam"
    },
    {
        "id": 20,
        "name": "Ferry",
        "type": "Queer Bar",
        "latitude": 51.9170151,
        "longitude": 4.4729362,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Westblaak 127, 3012 KJ Rotterdam",
        "tags": ["bar", "LGBTQ+", "nightlife", "events", "queer bar",
            "LGBTQ+",
            "nightlife",
            "DJ nights",
            "drag shows",
            "karaoke",
            "terrace",
            "two floors",
            "events",
            "inclusive",
            "friendly",
            "Centrum",
            "Westblaak",
            "evening",
            "social"],
        "languages": ["NL", "EN"],
        "description": "Ferry is a vibrant queer bar and café offering a welcoming space with two floors and a terrace. It hosts regular events, including DJ nights and drag performances.",
        "opening_times": {
            "monday_open": "16:00",
            "monday_close": "00:00",
            "tuesday_open": "16:00",
            "tuesday_close": "00:00",
            "wednesday_open": "16:00",
            "wednesday_close": "00:00",
            "thursday_open": "16:00",
            "thursday_close": "01:00",
            "friday_open": "16:00",
            "friday_close": "02:30",
            "saturday_open": "14:00",
            "saturday_close": "02:30",
            "sunday_open": "14:00",
            "sunday_close": "22:00"
        },
        "logo": "require('@/assets/images/placesdemo/ferry.png')",
        "website": "https://www.ferryrotterdam.com/",
        "google_maps_link": "https://maps.google.com/?q=Ferry+Rotterdam"
    },
    {
        "id": 21,
        "name": "Cinerama",
        "type": "Cinema",
        "latitude": 51.9170756,
        "longitude": 4.4762712,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Westblaak 18, 3012 KL Rotterdam",
        "tags": ["cinema", "arthouse", "films", "culture", "cinema",
            "arthouse films",
            "mainstream films",
            "film festivals",
            "historic venue",
            "seven screens",
            "cultural",
            "Centrum",
            "Westblaak",
            "indoor activity",
            "film enthusiasts",
            "diverse programming",
            "Kinepolis Group",
            "comfortable seating",
            "evening entertainment"],
        "languages": ["NL", "EN"],
        "description": "Cinerama is a historic cinema featuring seven screens and a mix of mainstream and arthouse films. It also hosts various film festivals throughout the year.",
        "opening_times": {
            "monday_open": "12:30",
            "monday_close": "00:00",
            "tuesday_open": "12:30",
            "tuesday_close": "00:00",
            "wednesday_open": "12:30",
            "wednesday_close": "00:00",
            "thursday_open": "12:30",
            "thursday_close": "00:00",
            "friday_open": "12:30",
            "friday_close": "00:00",
            "saturday_open": "12:30",
            "saturday_close": "00:00",
            "sunday_open": "12:30",
            "sunday_close": "00:00"
        },
        "logo": "require('@/assets/images/placesdemo/ferry.png')",
        "website": "https://www.cineramabios.nl/",
        "google_maps_link": "https://maps.google.com/?q=Cinerama+Rotterdam"
    },
    {
        "id": 22,
        "name": "De Slegte",
        "type": "Bookstore",
        "latitude": 51.9210891,
        "longitude": 4.4838334,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Hoogstraat 141, 3011 PM Rotterdam",
        "tags": ["bookstore", "secondhand", "study books", "literature", "bookstore",
            "secondhand books",
            "study materials",
            "literature",
            "collectibles",
            "reading",
            "academic",
            "Hoogstraat",
            "Centrum",
            "quiet",
            "indoor",
            "browsing",
            "affordable",
            "historic",
            "literary"],
        "languages": ["NL", "EN"],
        "description": "De Slegte is a renowned bookstore in Rotterdam, offering a vast collection of secondhand books, study materials, and literary works. It's a haven for book enthusiasts seeking both classic and contemporary titles.",
        "opening_times": {
            "monday_open": "12:00",
            "monday_close": "18:00",
            "tuesday_open": "10:00",
            "tuesday_close": "18:00",
            "wednesday_open": "10:00",
            "wednesday_close": "18:00",
            "thursday_open": "10:00",
            "thursday_close": "18:00",
            "friday_open": "10:00",
            "friday_close": "21:00",
            "saturday_open": "10:00",
            "saturday_close": "18:00",
            "sunday_open": "12:00",
            "sunday_close": "17:00"
        },
        "logo": "require('@/assets/images/placesdemo/de-slegte.png')",
        "website": "https://www.deslegte.com/rotterdam/",
        "google_maps_link": "https://maps.google.com/?q=De+Slegte+Rotterdam"
    },
    {
        "id": 23,
        "name": "Toffler",
        "type": "Nightclub",
        "latitude": 51.9235959,
        "longitude": 4.4728292,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Weena-Zuid 33, 3012 NH Rotterdam",
        "tags": ["nightclub", "electronic music", "underground", "techno", "nightclub",
            "electronic music",
            "techno",
            "underground",
            "intimate",
            "metro tunnel",
            "late-night",
            "dance",
            "Centrum",
            "Weena-Zuid",
            "youthful crowd",
            "weekend",
            "DJ sets",
            "vibrant",
            "music venue"],
        "languages": ["NL", "EN"],
        "description": "Toffler is an iconic underground nightclub located in a former metro tunnel beneath Weena. Known for its intimate atmosphere and cutting-edge electronic music, it's a staple in Rotterdam's nightlife scene.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "Closed",
            "tuesday_close": "Closed",
            "wednesday_open": "Closed",
            "wednesday_close": "Closed",
            "thursday_open": "Closed",
            "thursday_close": "Closed",
            "friday_open": "23:00",
            "friday_close": "06:00",
            "saturday_open": "23:00",
            "saturday_close": "06:00",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": "require('@/assets/images/placesdemo/toffler.png')",
        "website": "https://www.toffler.nl/",
        "google_maps_link": "https://maps.google.com/?q=Toffler+Rotterdam"
    },
    {
        "id": 24,
        "name": "Annabel",
        "type": "Music Venue",
        "latitude": 51.9253806,
        "longitude": 4.4734658,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Schiestraat 20, 3013 AH Rotterdam",
        "tags": ["music venue", "concerts", "club nights", "live music", "music venue",
            "concerts",
            "club nights",
            "live music",
            "pop venue",
            "terrace",
            "Central Station",
            "Schiestraat",
            "diverse genres",
            "large capacity",
            "events",
            "dance",
            "Centrum",
            "nightlife",
            "entertainment"],
        "languages": ["NL", "EN"],
        "description": "Annabel is Rotterdam's largest pop venue, hosting a diverse range of concerts and club nights. Located near Central Station, it features a spacious terrace and a vibrant atmosphere for music enthusiasts.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "11:00",
            "tuesday_close": "05:00",
            "wednesday_open": "11:00",
            "wednesday_close": "05:00",
            "thursday_open": "11:00",
            "thursday_close": "04:00",
            "friday_open": "11:00",
            "friday_close": "04:00",
            "saturday_open": "17:00",
            "saturday_close": "04:00",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": "require('@/assets/images/placesdemo/annabel.png')",
        "website": "https://www.annabel.nu/",
        "google_maps_link": "https://maps.google.com/?q=Annabel+Rotterdam"
    },
    {
        "id": 25,
        "name": "Teds op het dak",
        "type": "Café",
        "latitude": 51.9256766,
        "longitude": 4.4740312,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Schiekade 189, 3013 BR Rotterdam",
        "tags": ["café", "rooftop", "brunch", "panoramic views", "café",
            "rooftop",
            "brunch",
            "panoramic views",
            "all-day breakfast",
            "Schieblock building",
            "green setting",
            "relaxed",
            "urban garden",
            "Centrum",
            "Schiekade",
            "daytime",
            "casual dining",
            "social",
            "outdoor seating"],
        "languages": ["NL", "EN"],
        "description": "Teds op het dak is a charming rooftop café offering all-day brunch with stunning views of Rotterdam's skyline. Nestled atop the Schieblock building, it's a perfect spot for a relaxed meal in a lush setting.",
        "opening_times": {
            "monday_open": "10:00",
            "monday_close": "17:00",
            "tuesday_open": "10:00",
            "tuesday_close": "17:00",
            "wednesday_open": "10:00",
            "wednesday_close": "17:00",
            "thursday_open": "10:00",
            "thursday_close": "17:00",
            "friday_open": "10:00",
            "friday_close": "20:00",
            "saturday_open": "09:00",
            "saturday_close": "20:00",
            "sunday_open": "09:00",
            "sunday_close": "20:00"
        },
        "logo": "require('@/assets/images/placesdemo/teds.png')",
        "website": "https://teds-place.nl/locations/rotterdam-op-t-dak/",
        "google_maps_link": "https://maps.google.com/?q=Teds+op+het+dak+Rotterdam"
    },
    {
        "id": 26,
        "name": "Perron",
        "type": "Nightclub",
        "latitude": 51.9254191,
        "longitude": 4.4721746,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Schiestraat 42, 3013 AH Rotterdam",
        "tags": ["nightlife", "techno", "underground", "nightclub",
            "techno",
            "underground",
            "electronic music",
            "late-night",
            "Schiestraat",
            "Centrum",
            "industrial",
            "dance",
            "DJ sets",
            "youthful crowd",
            "weekend",
            "vibrant",
            "music venue",
            "nightlife"],
        "languages": ["NL", "EN"],
        "description": "Perron is a renowned nightclub in Rotterdam, celebrated for its electrifying techno beats and vibrant atmosphere, attracting both locals and tourists.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "Closed",
            "tuesday_close": "Closed",
            "wednesday_open": "Closed",
            "wednesday_close": "Closed",
            "thursday_open": "Closed",
            "thursday_close": "Closed",
            "friday_open": "23:59",
            "friday_close": "06:00",
            "saturday_open": "23:59",
            "saturday_close": "06:00",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": "https://www.perron.nl/assets/images/logo.png",
        "website": "https://www.perron.nl/",
        "google_maps_link": "https://maps.google.com/?q=Perron+Rotterdam"
    },
    {
        "id": 27,
        "name": "Roodkapje",
        "type": "Cultural Center",
        "latitude": 51.9248886,
        "longitude": 4.471909,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Delftseplein 39, 3013 AA Rotterdam",
        "tags": ["art", "music", "community", "art", "music", "community", "experimental", "emerging artists", "creative hub", "interdisciplinary", "youth culture", "alternative", "exhibitions", "live performances", "workshops", "cultural events", "non-profit", "underground", "residency programs", "multidisciplinary", "DIY culture", "inclusive", "urban"],
        "languages": ["NL", "EN"],
        "description": "Roodkapje is a vibrant cultural hub in Rotterdam, known for its eclectic blend of art, music, and creative experimentation, serving as a dynamic venue for emerging talent.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "12:00",
            "tuesday_close": "22:00",
            "wednesday_open": "12:00",
            "wednesday_close": "22:00",
            "thursday_open": "12:00",
            "thursday_close": "23:00",
            "friday_open": "12:00",
            "friday_close": "23:00",
            "saturday_open": "12:00",
            "saturday_close": "23:00",
            "sunday_open": "12:00",
            "sunday_close": "22:00"
        },
        "logo": "https://roodkapje.org/assets/images/logo.png",
        "website": "https://roodkapje.org/",
        "google_maps_link": "https://maps.google.com/?q=Roodkapje+Rotterdam"
    },
    {
        "id": 28,
        "name": "Burgertrut",
        "type": "Restaurant",
        "latitude": 51.9248541,
        "longitude": 4.4720209,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Delftseplein 39, 3013 AA Rotterdam",
        "tags": ["restaurant", "vegan", "burgers", "restaurant", "vegan", "vegetarian", "organic", "burgers", "casual dining", "artsy", "affordable", "community-focused", "alternative", "homemade", "local ingredients", "inclusive", "cozy", "youthful", "creative space", "non-profit", "social hub", "eco-friendly", "urban"],
        "languages": ["NL", "EN"],
        "description": "Burgertrut is a cozy restaurant in Rotterdam offering a variety of homemade burgers, including vegan options, in a relaxed and artistic setting.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "12:00",
            "tuesday_close": "22:00",
            "wednesday_open": "12:00",
            "wednesday_close": "22:00",
            "thursday_open": "12:00",
            "thursday_close": "23:00",
            "friday_open": "12:00",
            "friday_close": "23:00",
            "saturday_open": "12:00",
            "saturday_close": "23:00",
            "sunday_open": "12:00",
            "sunday_close": "22:00"
        },
        "logo": "https://roodkapje.org/assets/images/logo.png",
        "website": "https://roodkapje.org/burgertrut/",
        "google_maps_link": "https://maps.google.com/?q=Burgertrut+Rotterdam"
    },
    {
        "id": 29,
        "name": "Fenix Food Factory",
        "type": "Food Market",
        "latitude": 51.9020098,
        "longitude": 4.4842887,
        "city": "Rotterdam",
        "district": "Katendrecht",
        "address": "Nico Koomanskade 1025, 3072 LM Rotterdam",
        "tags": ["food market", "local produce", "craft beer", "food market", "local produce", "craft beer", "artisanal", "culinary hub", "community space", "sustainable", "zero-waste", "organic", "farm-to-table", "indoor market", "events", "workshops", "family-friendly", "cultural", "urban", "trendy", "diverse cuisine", "social gathering", "eco-conscious"],
        "languages": ["NL", "EN"],
        "description": "Fenix Food Factory is a dynamic food market in Rotterdam, housed in a former warehouse, offering a variety of local produce, craft beers, and artisanal products.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "10:00",
            "tuesday_close": "22:00",
            "wednesday_open": "10:00",
            "wednesday_close": "22:00",
            "thursday_open": "10:00",
            "thursday_close": "22:00",
            "friday_open": "10:00",
            "friday_close": "22:00",
            "saturday_open": "09:30",
            "saturday_close": "22:00",
            "sunday_open": "09:30",
            "sunday_close": "21:00"
        },
        "logo": "https://www.fenixfoodfactory.nl/assets/images/logo.png",
        "website": "https://www.fenixfoodfactory.nl/",
        "google_maps_link": "https://maps.google.com/?q=Fenix+Food+Factory+Rotterdam"
    },
    {
        "id": 30,
        "name": "Kleine Walhalla",
        "type": "Theater",
        "latitude": 51.9015922,
        "longitude": 4.4826287,
        "city": "Rotterdam",
        "district": "Katendrecht",
        "address": "Sumatraweg 9-11, 3072 ZP Rotterdam",
        "tags": ["theater", "intimate", "local artists", "cultural venue", "performing arts", "community", "events", "live performances", "artistic", "cozy", "cabaret", "music", "youth theater", "inclusive", "experimental", "storytelling", "workshops", "neighborhood-focused", "accessible", "creative"],
        "languages": ["NL", "EN"],
        "description": "Kleine Walhalla is an intimate theater space in Rotterdam's Katendrecht district, hosting a variety of performances by both emerging and established artists.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "13:00",
            "tuesday_close": "16:00",
            "wednesday_open": "13:00",
            "wednesday_close": "16:00",
            "thursday_open": "13:00",
            "thursday_close": "16:00",
            "friday_open": "13:00",
            "friday_close": "16:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://www.theaterwalhalla.nl/",
        "google_maps_link": "https://maps.google.com/?q=Kleine+Walhalla+Rotterdam"
    },
    {
        "id": 31,
        "name": "Nieuwe Luxor Theater",
        "type": "Theater",
        "latitude": 51.907128,
        "longitude": 4.4883574,
        "city": "Rotterdam",
        "district": "Kop van Zuid",
        "address": "Posthumalaan 1, 3072 AG Rotterdam",
        "tags": ["theater", "modern", "large capacity", "musicals", "concerts", "dance", "opera", "cabaret", "international productions", "cultural hub", "family-friendly", "mainstream", "accessible", "events", "performing arts", "entertainment", "urban", "professional", "diverse programming", "landmark"],
        "languages": ["NL", "EN"],
        "description": "Nieuwe Luxor Theater is a modern performing arts venue located at the foot of the Erasmus Bridge in Rotterdam, known for hosting a wide range of large-scale productions.",
        "opening_times": {
            "monday_open": "10:00",
            "monday_close": "18:00",
            "tuesday_open": "10:00",
            "tuesday_close": "18:00",
            "wednesday_open": "10:00",
            "wednesday_close": "18:00",
            "thursday_open": "10:00",
            "thursday_close": "18:00",
            "friday_open": "10:00",
            "friday_close": "18:00",
            "saturday_open": "12:00",
            "saturday_close": "18:00",
            "sunday_open": "12:00",
            "sunday_close": "18:00"
        },
        "logo": null,
        "website": "https://www.luxortheater.nl/",
        "google_maps_link": "https://maps.google.com/?q=Nieuwe+Luxor+Theater+Rotterdam"
    },
    {
        "id": 32,
        "name": "LantarenVenster",
        "type": "Cinema",
        "latitude": 51.9048318,
        "longitude": 4.4844183,
        "city": "Rotterdam",
        "district": "Kop van Zuid",
        "address": "Otto Reuchlinweg 996, 3072 MD Rotterdam",
        "tags": ["cinema", "jazz", "film screenings", "concerts", "festivals", "cultural events", "restaurant", "art house", "live music", "educational programs", "independent films", "documentaries", "world cinema", "inclusive", "community space", "urban", "creative", "diverse programming", "cultural hub", "modern"],
        "languages": ["NL", "EN"],
        "description": "LantarenVenster is a cultural venue in Rotterdam offering a diverse program of films, jazz concerts, and festivals, along with a restaurant and educational activities.",
        "opening_times": {
            "monday_open": "11:30",
            "monday_close": "01:00",
            "tuesday_open": "11:30",
            "tuesday_close": "01:00",
            "wednesday_open": "11:30",
            "wednesday_close": "01:00",
            "thursday_open": "11:30",
            "thursday_close": "01:00",
            "friday_open": "11:30",
            "friday_close": "01:00",
            "saturday_open": "09:30",
            "saturday_close": "01:00",
            "sunday_open": "09:30",
            "sunday_close": "01:00"
        },
        "logo": null,
        "website": "https://www.lantarenvenster.nl/",
        "google_maps_link": "https://maps.google.com/?q=LantarenVenster+Rotterdam"
    },
    {
        "id": 33,
        "name": "Historische Tuin Schoonoord",
        "type": "Park",
        "latitude": 51.9086472,
        "longitude": 4.4701521,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Kievitslaan 8, 3016 CG Rotterdam",
        "tags": ["park", "historic garden", "greenery", "tranquil", "nature", "walking paths", "botanical", "relaxation", "scenic", "urban oasis", "heritage site", "flora and fauna", "educational", "family-friendly", "photography", "birdwatching", "seasonal blooms", "meditative", "accessible", "hidden gem"],
        "languages": ["NL", "EN"],
        "description": "Historische Tuin Schoonoord is a serene historic garden in the heart of Rotterdam, offering visitors a peaceful retreat amidst lush greenery and diverse plant species.",
        "opening_times": {
            "monday_open": "08:30",
            "monday_close": "16:30",
            "tuesday_open": "08:30",
            "tuesday_close": "16:30",
            "wednesday_open": "08:30",
            "wednesday_close": "16:30",
            "thursday_open": "08:30",
            "thursday_close": "16:30",
            "friday_open": "08:30",
            "friday_close": "16:30",
            "saturday_open": "08:30",
            "saturday_close": "16:30",
            "sunday_open": "08:30",
            "sunday_close": "16:30"
        },
        "logo": null,
        "website": "https://tuinschoonoord.nl/",
        "google_maps_link": "https://maps.google.com/?q=Historische+Tuin+Schoonoord+Rotterdam"
    },
    {
        "id": 34,
        "name": "Mystiek",
        "type": "Store",
        "latitude": 51.9163654,
        "longitude": 4.4771888,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Schiedamse Vest 89B, 3012 BG Rotterdam",
        "tags": ["alternative", "metaphysical", "spirituality", "crystals", "books", "incense", "holistic", "wellness", "meditation", "esoteric", "self-help", "new age", "healing", "mindfulness", "tarot", "astrology", "workshops", "community", "independent", "urban"],
        "languages": ["NL", "EN"],
        "description": " ",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "Closed",
            "tuesday_close": "Closed",
            "wednesday_open": "Closed",
            "wednesday_close": "Closed",
            "thursday_open": "22:00",
            "thursday_close": "04:00",
            "friday_open": "22:00",
            "friday_close": "05:00",
            "saturday_open": "22:00",
            "saturday_close": "05:00",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://mystiek.nl/",
        "google_maps_link": "https://maps.google.com/?q=Mystiek+Rotterdam"
    },
    {
        "id": 35,
        "name": "Boekhandel van Gennep",
        "type": "Bookstore",
        "latitude": 51.9172815,
        "longitude": 4.4709029,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Oude Binnenweg 131B, 3012 JD Rotterdam",
        "tags": ["bookstore", "literature", "poetry", "art books", "children's books", "photography", "cozy", "independent", "readings", "cultural", "local authors", "community events", "intellectual", "historic", "literary hub", "inclusive", "educational", "urban", "creative", "niche"], "languages": ["NL", "EN"],
        "description": "Boekhandel van Gennep is a cozy independent bookstore in Rotterdam offering a curated selection of literature, poetry, art, and photography books, along with regular author readings.",
        "opening_times": {
            "monday_open": "12:00",
            "monday_close": "18:00",
            "tuesday_open": "10:00",
            "tuesday_close": "18:00",
            "wednesday_open": "10:00",
            "wednesday_close": "18:00",
            "thursday_open": "10:00",
            "thursday_close": "18:00",
            "friday_open": "10:00",
            "friday_close": "18:00",
            "saturday_open": "10:00",
            "saturday_close": "17:00",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "http://www.boekhandelvangennep.nl/",
        "google_maps_link": "https://maps.google.com/?q=Boekhandel+van+Gennep+Rotterdam"
    },
    {
        "id": 36,
        "name": "Rejoes",
        "type": "Second Hand Clothing Store",
        "latitude": 51.9176524,
        "longitude": 4.4766628,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Oude Binnenweg 34, 3012 JE Rotterdam",
        "tags": ["second-hand", "vintage", "fashion", "sustainable", "affordable", "urban", "casual", "unisex", "trendy", "streetwear", "eco-friendly", "unique finds", "retro", "youthful", "independent", "upcycled", "diverse styles", "inclusive", "creative", "shopping"],
        "languages": ["NL", "EN"],
        "description": "Rejoes is a popular second-hand fashion store offering a wide range of vintage clothing and accessories for both men and women.",
        "opening_times": {
            "monday_open": "11:00",
            "monday_close": "19:30",
            "tuesday_open": "10:00",
            "tuesday_close": "20:00",
            "wednesday_open": "10:00",
            "wednesday_close": "20:00",
            "thursday_open": "10:00",
            "thursday_close": "20:00",
            "friday_open": "10:00",
            "friday_close": "20:00",
            "saturday_open": "10:00",
            "saturday_close": "20:00",
            "sunday_open": "12:00",
            "sunday_close": "18:30"
        },
        "logo": "https://rejoes.com/",
        "website": "https://rejoes.com/",
        "google_maps_link": "https://maps.google.com/?q=Kilo+Kilo+store+Rotterdam"
    },
    {
        "id": 37,
        "name": "De Après Skihut",
        "type": "Bar",
        "latitude": 51.9223802,
        "longitude": 4.4741391,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Stadhuisplein 29, 3012 AR Rotterdam",
        "tags": ["bar", "party", "après-ski", "music", "dance", "nightlife", "drinks", "fun", "entertainment", "themed", "lively", "youthful", "social", "festive", "DJ", "karaoke", "casual", "urban", "popular", "energetic"],
        "languages": ["NL", "EN"],
        "description": "De Après Skihut is a vibrant après-ski themed bar offering lively music, dancing, and a festive atmosphere reminiscent of alpine parties.",
        "opening_times": {
            "monday_open": "10:00",
            "monday_close": "04:00",
            "tuesday_open": "10:00",
            "tuesday_close": "04:00",
            "wednesday_open": "10:00",
            "wednesday_close": "04:00",
            "thursday_open": "10:00",
            "thursday_close": "04:00",
            "friday_open": "10:00",
            "friday_close": "05:00",
            "saturday_open": "10:00",
            "saturday_close": "05:00",
            "sunday_open": "10:00",
            "sunday_close": "04:00"
        },
        "logo": "https://deapresskihut.nl/",
        "website": "https://deapresskihut.nl/en/",
        "google_maps_link": "https://maps.google.com/?q=De+Après+Skihut+Rotterdam"
    },
    {
        "id": 38,
        "name": "De Gele Kanarie Cafe",
        "type": "Bar",
        "latitude": 51.9228109,
        "longitude": 4.4859978,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Goudsesingel 284, 3011 KH Rotterdam",
        "tags": ["bar", "cafe", "beer", "food", "lunch", "dinner", "craft beer", "cozy", "modern", "social", "brewery", "casual dining", "urban", "trendy", "friendly", "events", "local", "inclusive", "relaxed", "gathering spot"],
        "languages": ["NL", "EN"],
        "description": "De Gele Kanarie Cafe is a modern bar and cafe known for its own brewed beer, offering a cozy atmosphere for lunch, dinner, and drinks.",
        "opening_times": {
            "monday_open": "15:00",
            "monday_close": "01:00",
            "tuesday_open": "15:00",
            "tuesday_close": "01:00",
            "wednesday_open": "15:00",
            "wednesday_close": "01:00",
            "thursday_open": "15:00",
            "thursday_close": "01:00",
            "friday_open": "15:00",
            "friday_close": "01:00",
            "saturday_open": "12:00",
            "saturday_close": "01:00",
            "sunday_open": "12:00",
            "sunday_close": "23:00"
        },
        "logo": "https://www.degelekanarie.com/",
        "website": "https://www.degelekanarie.nl/",
        "google_maps_link": "https://maps.google.com/?q=De+Gele+Kanarie+Cafe+Rotterdam"
    },
    {
        "id": 39,
        "name": "Deli Tasty",
        "type": "Restaurant",
        "latitude": 51.9233262,
        "longitude": 4.482632,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Meent 40, 3011 JL Rotterdam",
        "tags": ["restaurant", "Vietnamese", "Asian", "lunch", "dinner", "halal", "authentic", "cozy", "family-friendly", "affordable", "takeout", "casual dining", "urban", "spicy", "traditional", "friendly", "inclusive", "quick service", "popular", "cultural"],
        "languages": ["NL", "EN"],
        "description": "Deli Tasty is an authentic Vietnamese restaurant offering a variety of traditional dishes in a cozy and family-friendly setting.",
        "opening_times": {
            "monday_open": "12:00",
            "monday_close": "22:00",
            "tuesday_open": "12:00",
            "tuesday_close": "22:00",
            "wednesday_open": "12:00",
            "wednesday_close": "22:00",
            "thursday_open": "12:00",
            "thursday_close": "22:00",
            "friday_open": "12:00",
            "friday_close": "22:00",
            "saturday_open": "12:00",
            "saturday_close": "22:00",
            "sunday_open": "12:00",
            "sunday_close": "22:00"
        },
        "logo": "https://delitasty.nl/",
        "website": "https://delitasty.nl/",
        "google_maps_link": "https://maps.google.com/?q=Deli+Tasty+Rotterdam"
    },
    {
        "id": 40,
        "name": "Cheap Fashion",
        "type": "Second Hand Clothing Store",
        "latitude": 51.9237678,
        "longitude": 4.4828559,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Meent 25, 3011 JB Rotterdam",
        "tags": ["second-hand", "vintage", "fashion", "affordable", "retro", "unique", "sustainable", "casual", "unisex", "eclectic", "urban", "youthful", "independent", "trendy", "diverse styles", "creative", "eco-friendly", "shopping", "inclusive", "stylish"],
        "languages": ["NL", "EN"],
        "description": "Cheap Fashion is a well-known vintage store offering a diverse range of affordable second-hand clothing and accessories for all styles.",
        "opening_times": {
            "monday_open": "11:00",
            "monday_close": "18:00",
            "tuesday_open": "10:00",
            "tuesday_close": "18:00",
            "wednesday_open": "10:00",
            "wednesday_close": "18:00",
            "thursday_open": "10:00",
            "thursday_close": "18:00",
            "friday_open": "10:00",
            "friday_close": "18:00",
            "saturday_open": "10:00",
            "saturday_close": "18:00",
            "sunday_open": "12:00",
            "sunday_close": "17:00"
        },
        "logo": "https://rotterdam.info/locaties/cheap-fashion/",
        "website": "https://www.facebook.com/p/Cheap-Fashion-100046132787637/",
        "google_maps_link": "https://maps.google.com/?q=Cheap+Fashion+Rotterdam"
    },
    {
        "id": 41,
        "name": "Pebbles Kitty Cat Café",
        "type": "Cat Café",
        "latitude": 51.9229726,
        "longitude": 4.4918148,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Hoogstraat 30A, 3011 PR Rotterdam",
        "tags": ["cat café", "coffee", "tea", "cats", "board games", "vegan options", "relaxing", "cozy", "pet-friendly", "desserts", "family-friendly", "casual", "urban", "social", "inclusive", "unique", "friendly", "community", "snacks", "entertainment"],
        "languages": ["NL", "EN"],
        "description": "Pebbles Kitty Cat Café is Rotterdam's first and only cat café, offering a cozy environment where visitors can enjoy coffee, tea, and treats while interacting with resident cats.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "12:00",
            "tuesday_close": "17:00",
            "wednesday_open": "12:00",
            "wednesday_close": "17:00",
            "thursday_open": "12:00",
            "thursday_close": "17:00",
            "friday_open": "12:00",
            "friday_close": "17:00",
            "saturday_open": "10:30",
            "saturday_close": "17:00",
            "sunday_open": "10:30",
            "sunday_close": "17:00"
        },
        "logo": "require('@/assets/images/placesdemo/pebbles-kitty-cat-cafe.png')",
        "website": "https://pebbleskittycatcafe.nl/en/",
        "google_maps_link": "https://maps.google.com/?q=Pebbles+Kitty+Cat+Café+Rotterdam"
    },
    {
        "id": 42,
        "name": "The Social Hub Rotterdam",
        "type": "Hotel & Co-working Space",
        "latitude": 51.9212788,
        "longitude": 4.502891,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Willem Ruyslaan 225, 3063 ER Rotterdam",
        "tags": ["hotel", "co-working", "student housing", "events", "restaurant", "gym", "community", "networking", "modern", "urban", "inclusive", "creative", "flexible spaces", "international", "youthful", "innovative", "social", "collaborative", "accommodation", "lifestyle"],
        "languages": ["NL", "EN"],
        "description": "The Social Hub Rotterdam is a hybrid hospitality concept combining hotel accommodations, student housing, co-working spaces, and event venues, fostering a vibrant community for travelers, students, and professionals.",
        "opening_times": {
            "monday_open": "00:00",
            "monday_close": "23:59",
            "tuesday_open": "00:00",
            "tuesday_close": "23:59",
            "wednesday_open": "00:00",
            "wednesday_close": "23:59",
            "thursday_open": "00:00",
            "thursday_close": "23:59",
            "friday_open": "00:00",
            "friday_close": "23:59",
            "saturday_open": "00:00",
            "saturday_close": "23:59",
            "sunday_open": "00:00",
            "sunday_close": "23:59"
        },
        "logo": "require('@/assets/images/placesdemo/the-social-hub-rotterdam.png')",
        "website": "https://www.thesocialhub.co/rotterdam/",
        "google_maps_link": "https://maps.google.com/?q=The+Social+Hub+Rotterdam"
    },
    {
        "id": 43,
        "name": "Skate Fever",
        "type": "Sports",
        "latitude": 51.924714,
        "longitude": 4.5639559,
        "city": "Rotterdam",
        "district": "Feijenoord",
        "address": "Rhijnspoor 275, 2901 LB Capelle aan den IJssel",
        "tags": ["roller skating", "disco", "family fun", "music", "events", "birthday parties", "skate rental", "indoor", "sports", "entertainment", "youthful", "active", "social", "inclusive", "urban", "casual", "fun", "recreational", "community", "vibrant"],
        "languages": ["NL", "EN"],
        "description": "Skate Fever is an indoor roller disco offering a vibrant atmosphere with music, lights, and skating fun for all ages, perfect for parties and events.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "Closed",
            "tuesday_close": "Closed",
            "wednesday_open": "14:00",
            "wednesday_close": "22:00",
            "thursday_open": "14:00",
            "thursday_close": "22:00",
            "friday_open": "14:00",
            "friday_close": "23:00",
            "saturday_open": "12:00",
            "saturday_close": "23:00",
            "sunday_open": "12:00",
            "sunday_close": "22:00"
        },
        "logo": "require('@/assets/images/placesdemo/skate-fever.png')",
        "website": "https://skate-fever.com/",
        "google_maps_link": "https://maps.google.com/?q=Skate+Fever+Rotterdam"
    },
    {
        "id": 44,
        "name": "Hollywood Entertainment Center",
        "type": "Arcade & Bowling",
        "latitude": 51.8961215,
        "longitude": 4.522459,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Cor Kieboomplein 513, 3077 MK Rotterdam",
        "tags": ["arcade", "bowling", "escape rooms", "minigolf", "sports bar", "family entertainment", "VR games", "events", "dining", "leisure", "indoor", "fun", "casual", "urban", "group activities", "youthful", "social", "inclusive", "recreational", "modern"],
        "languages": ["NL", "EN"],
        "description": "Hollywood Entertainment Center is a multifaceted leisure venue featuring arcade games, bowling alleys, escape rooms, minigolf, and dining options, catering to all age groups.",
        "opening_times": {
            "monday_open": "11:00",
            "monday_close": "23:00",
            "tuesday_open": "11:00",
            "tuesday_close": "23:00",
            "wednesday_open": "11:00",
            "wednesday_close": "23:00",
            "thursday_open": "11:00",
            "thursday_close": "23:00",
            "friday_open": "11:00",
            "friday_close": "01:00",
            "saturday_open": "11:00",
            "saturday_close": "01:00",
            "sunday_open": "11:00",
            "sunday_close": "23:00"
        },
        "logo": "require('@/assets/images/placesdemo/hollywood-entertainment-center.png')",
        "website": "https://www.hollywood.nl/rotterdam",
        "google_maps_link": "https://maps.google.com/?q=Hollywood+Entertainment+Center+Rotterdam"
    },
    {
        "id": 45,
        "name": "Gamestate de Kuip",
        "type": "Arcade",
        "latitude": 51.8968932,
        "longitude": 4.5222146,
        "city": "Rotterdam",
        "district": "Feijenoord",
        "address": "Cor Kieboomplein 109, 3077 MK Rotterdam",
        "tags": ["arcade", "gaming", "family fun", "ticket redemption", "modern games", "entertainment", "indoor", "fun zone", "video games", "leisure", "arcade",
            "gaming",
            "family-friendly",
            "indoor",
            "entertainment",
            "ticket redemption",
            "modern games",
            "video games",
            "youth",
            "group activities",
            "casual",
            "fun zone",
            "interactive",
            "digital entertainment",
            "leisure",
            "social gathering",
            "competitive",
            "urban"],
        "languages": ["NL", "EN"],
        "description": "Gamestate de Kuip is a modern arcade offering a wide range of games for all ages, from classic machines to the latest gaming experiences.",
        "opening_times": {
            "monday_open": "12:00",
            "monday_close": "00:00",
            "tuesday_open": "12:00",
            "tuesday_close": "00:00",
            "wednesday_open": "12:00",
            "wednesday_close": "00:00",
            "thursday_open": "12:00",
            "thursday_close": "00:00",
            "friday_open": "12:00",
            "friday_close": "01:00",
            "saturday_open": "12:00",
            "saturday_close": "01:00",
            "sunday_open": "12:00",
            "sunday_close": "00:00"
        },
        "logo": "require('@/assets/images/placesdemo/gamestate-de-kuip.png')",
        "website": "https://gamestate.com/pages/rotterdam",
        "google_maps_link": "https://maps.google.com/?q=Gamestate+de+Kuip+Rotterdam"
    },
    {
        "id": 46,
        "name": "Pathé Schouwburgplein",
        "type": "Cinema",
        "latitude": 51.9207891,
        "longitude": 4.4708331,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Schouwburgplein 101, 3012 CL Rotterdam",
        "tags": ["cinema", "IMAX", "movies", "entertainment", "city center", "modern", "accessible", "film", "Rotterdam", "theater", "cinema",
            "IMAX",
            "movies",
            "entertainment",
            "city center",
            "modern",
            "accessible",
            "film",
            "Rotterdam",
            "theater",
            "blockbusters",
            "independent films",
            "family-friendly",
            "date night",
            "cultural events",
            "comfortable seating",
            "audio-visual experience",
            "night out"],
        "languages": ["NL", "EN", "Other"],
        "description": "Pathé Schouwburgplein is a modern cinema located in the heart of Rotterdam, featuring 7 halls equipped with IMAX technology and luxurious seating. It's a popular destination for movie enthusiasts seeking the latest films in a comfortable setting.",
        "opening_times": {
            "monday_open": "10:00",
            "monday_close": "00:00",
            "tuesday_open": "10:00",
            "tuesday_close": "00:00",
            "wednesday_open": "10:00",
            "wednesday_close": "00:00",
            "thursday_open": "10:00",
            "thursday_close": "00:00",
            "friday_open": "10:00",
            "friday_close": "00:00",
            "saturday_open": "10:00",
            "saturday_close": "00:00",
            "sunday_open": "10:00",
            "sunday_close": "00:00"
        },
        "logo": "require('@/assets/images/placesdemo/pathe-schouwburgplein.png')",
        "website": "https://www.pathe.nl/en/cinemas/pathe-schouwburgplein",
        "google_maps_link": "https://maps.google.com/?q=Pathé+Schouwburgplein+Rotterdam"
    },
    {
        "id": 47,
        "name": "Baroeg",
        "type": "Music Venue",
        "latitude": 51.876749,
        "longitude": 4.5164991,
        "city": "Rotterdam",
        "district": "Lombardijen",
        "address": "Spinozaweg 300, 3076 ET Rotterdam",
        "tags": ["music", "venue", "alternative", "concerts", "subculture", "live music", "Rotterdam", "events", "nightlife", "bar", "music",
            "venue",
            "alternative",
            "concerts",
            "subculture",
            "live music",
            "Rotterdam",
            "events",
            "nightlife",
            "bar",
            "metal",
            "punk",
            "hardcore",
            "underground",
            "dance nights",
            "youth culture",
            "intimate setting",
            "local artists"],
        "languages": ["NL", "EN", "Other"],
        "description": "Baroeg is a renowned music venue in Rotterdam, known for its focus on alternative and subcultural music genres. Hosting live concerts and events, it serves as a hub for music enthusiasts seeking unique performances.",
        "opening_times": {
            "monday_open": "18:00",
            "monday_close": "00:00",
            "tuesday_open": "18:00",
            "tuesday_close": "00:00",
            "wednesday_open": "18:00",
            "wednesday_close": "00:00",
            "thursday_open": "18:00",
            "thursday_close": "00:00",
            "friday_open": "18:00",
            "friday_close": "01:00",
            "saturday_open": "18:00",
            "saturday_close": "01:00",
            "sunday_open": "18:00",
            "sunday_close": "01:00"
        },
        "logo": "require('@/assets/images/placesdemo/baroeg.png')",
        "website": "https://baroeg.nl/",
        "google_maps_link": "https://maps.google.com/?q=Baroeg+Rotterdam"
    },
    {
        "id": 48,
        "name": "Vessel 11",
        "type": "Music Venue & Restaurant",
        "latitude": 51.9172122,
        "longitude": 4.4834674,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Wijnhaven 101, 3011 WN Rotterdam",
        "tags": ["music", "restaurant", "bar", "live music", "ship", "unique venue", "Rotterdam", "events", "dining", "entertainment", "music",
            "restaurant",
            "bar",
            "live music",
            "ship",
            "unique venue",
            "Rotterdam",
            "events",
            "dining",
            "entertainment",
            "British cuisine",
            "gastropub",
            "waterfront",
            "intimate",
            "cultural events",
            "brunch",
            "dinner",
            "social gathering"],
        "languages": ["NL", "EN", "Other"],
        "description": "Vessel 11 is a unique music venue and restaurant located on a red lightship in Rotterdam's Wijnhaven. Offering live music performances and a British-inspired menu, it provides a distinctive experience for visitors.",
        "opening_times": {
            "monday_open": "Closed",
            "monday_close": "Closed",
            "tuesday_open": "12:00",
            "tuesday_close": "00:00",
            "wednesday_open": "12:00",
            "wednesday_close": "00:00",
            "thursday_open": "12:00",
            "thursday_close": "00:00",
            "friday_open": "12:00",
            "friday_close": "01:00",
            "saturday_open": "11:00",
            "saturday_close": "01:00",
            "sunday_open": "11:00",
            "sunday_close": "00:00"
        },
        "logo": "require('@/assets/images/placesdemo/vessel11.png')",
        "website": "https://www.vessel11.nl/en/",
        "google_maps_link": "https://maps.google.com/?q=Vessel+11+Rotterdam"
    },
    {
        "id": 49,
        "name": "Tuincentrum De Molen",
        "type": "Garden Center",
        "latitude": 51.883457,
        "longitude": 4.4667266,
        "city": "Rotterdam",
        "district": "Overschie",
        "address": "Kromme Zandweg 81, 3082 PZ Rotterdam",
        "tags": ["garden", "center", "plants", "flowers", "outdoor", "indoor", "Rotterdam", "gardening", "nursery", "greenery", "garden",
            "center",
            "plants",
            "flowers",
            "outdoor",
            "indoor",
            "Rotterdam",
            "gardening",
            "nursery",
            "greenery",
            "home decor",
            "DIY",
            "workshops",
            "seasonal",
            "family-friendly",
            "nature",
            "leisure",
            "local business"],
        "languages": ["NL", "EN", "Other"],
        "description": "Tuincentrum De Molen is a comprehensive garden center in Rotterdam, offering a wide selection of plants, flowers, and gardening supplies. It's a go-to destination for gardening enthusiasts and professionals alike.",
        "opening_times": {
            "monday_open": "09:00",
            "monday_close": "17:00",
            "tuesday_open": "09:00",
            "tuesday_close": "17:00",
            "wednesday_open": "09:00",
            "wednesday_close": "17:00",
            "thursday_open": "09:00",
            "thursday_close": "17:00",
            "friday_open": "09:00",
            "friday_close": "17:00",
            "saturday_open": "09:00",
            "saturday_close": "17:00",
            "sunday_open": "12:00",
            "sunday_close": "17:00"
        },
        "logo": "require('@/assets/images/placesdemo/tuincentrum-de-molen.png')",
        "website": "https://www.bloemencentrum-demolen.nl/",
        "google_maps_link": "https://maps.google.com/?q=Tuincentrum+De+Molen+Rotterdam"
    },
    {
        "id": 50,
        "name": "Erasmus Volley",
        "type": "Sports Association",
        "latitude": 51.9175,
        "longitude": 4.5250,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        "tags": ["volleyball", "team sports", "students", "competition", "social", "training"],
        "languages": ["NL", "EN"],
        "description": "Erasmus Volley is the student volleyball association of Erasmus University Rotterdam, offering training sessions and competitions for various skill levels.",
        "opening_times": {
            "monday_open": "18:00",
            "monday_close": "22:00",
            "tuesday_open": "18:00",
            "tuesday_close": "22:00",
            "wednesday_open": "18:00",
            "wednesday_close": "22:00",
            "thursday_open": "18:00",
            "thursday_close": "22:00",
            "friday_open": "18:00",
            "friday_close": "22:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://erasmusvolley.nl",
        "google_maps_link": "https://maps.google.com/?q=Erasmus+Volley+Rotterdam"
    },
    {
        "id": 51,
        "name": "E.B.V. Baros",
        "type": "Sports Association",
        "latitude": 51.9175,
        "longitude": 4.5250,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        "tags": ["basketball", "team sports", "students", "competition", "training"],
        "languages": ["NL", "EN"],
        "description": "E.B.V. Baros is the student basketball association of Erasmus University Rotterdam, welcoming players of all levels for training and competitions.",
        "opening_times": {
            "monday_open": "18:00",
            "monday_close": "22:00",
            "tuesday_open": "18:00",
            "tuesday_close": "22:00",
            "wednesday_open": "18:00",
            "wednesday_close": "22:00",
            "thursday_open": "18:00",
            "thursday_close": "22:00",
            "friday_open": "18:00",
            "friday_close": "22:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://ebvbaros.nl",
        "google_maps_link": "https://maps.google.com/?q=E.B.V.+Baros+Rotterdam"
    },
    {
        "id": 52,
        "name": "A.R.S.R. Skadi",
        "type": "Sports Association",
        "latitude": 51.9320,
        "longitude": 4.4700,
        "city": "Rotterdam",
        "district": "Noord",
        "address": "Noorderkanaalweg 20-22, 3037 AV Rotterdam",
        "tags": ["rowing", "water sports", "students", "competition", "training"],
        "languages": ["NL", "EN"],
        "description": "A.R.S.R. Skadi is the student rowing club of Erasmus University Rotterdam, offering rowing opportunities for beginners and experienced rowers.",
        "opening_times": {
            "monday_open": "06:00",
            "monday_close": "22:00",
            "tuesday_open": "06:00",
            "tuesday_close": "22:00",
            "wednesday_open": "06:00",
            "wednesday_close": "22:00",
            "thursday_open": "06:00",
            "thursday_close": "22:00",
            "friday_open": "06:00",
            "friday_close": "22:00",
            "saturday_open": "08:00",
            "saturday_close": "18:00",
            "sunday_open": "08:00",
            "sunday_close": "18:00"
        },
        "logo": null,
        "website": "https://www.skadi.nl",
        "google_maps_link": "https://maps.google.com/?q=A.R.S.R.+Skadi+Rotterdam"
    },
    {
        "id": 53,
        "name": "R.S.T.V. Passing Shot",
        "type": "Sports Association",
        "latitude": 51.9175,
        "longitude": 4.5250,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        "tags": ["tennis", "racket sports", "students", "competition", "training"],
        "languages": ["NL", "EN"],
        "description": "R.S.T.V. Passing Shot is the student tennis association of Erasmus University Rotterdam, catering to players of all skill levels.",
        "opening_times": {
            "monday_open": "18:00",
            "monday_close": "22:00",
            "tuesday_open": "18:00",
            "tuesday_close": "22:00",
            "wednesday_open": "18:00",
            "wednesday_close": "22:00",
            "thursday_open": "18:00",
            "thursday_close": "22:00",
            "friday_open": "18:00",
            "friday_close": "22:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://passingshot.nl",
        "google_maps_link": "https://maps.google.com/?q=R.S.T.V.+Passing+Shot+Rotterdam"
    },
    {
        "id": 54,
        "name": "R.S.Z.&W.V. Ragnar",
        "type": "Sports Association",
        "latitude": 51.9270,
        "longitude": 4.5000,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Location varies, please check website",
        "tags": ["swimming", "water polo", "students", "competition", "training"],
        "languages": ["NL", "EN"],
        "description": "R.S.Z.&W.V. Ragnar is the student swimming and water polo association of Erasmus University Rotterdam, welcoming swimmers and water polo players.",
        "opening_times": {
            "monday_open": "18:00",
            "monday_close": "22:00",
            "tuesday_open": "18:00",
            "tuesday_close": "22:00",
            "wednesday_open": "18:00",
            "wednesday_close": "22:00",
            "thursday_open": "18:00",
            "thursday_close": "22:00",
            "friday_open": "18:00",
            "friday_close": "22:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://ragnar-rotterdam.nl",
        "google_maps_link": "https://maps.google.com/?q=R.S.Z.&W.V.+Ragnar+Rotterdam"
    },
    {
        "id": 55,
        "name": "Erasmus Padel Association",
        "type": "Sports Association",
        "latitude": 51.9175,
        "longitude": 4.5250,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        "tags": ["padel", "racket sports", "students", "competition", "training"],
        "languages": ["NL", "EN"],
        "description": "Erasmus Padel Association is the student padel club of Erasmus University Rotterdam, offering training and matches for all levels.",
        "opening_times": {
            "monday_open": "18:00",
            "monday_close": "22:00",
            "tuesday_open": "18:00",
            "tuesday_close": "22:00",
            "wednesday_open": "18:00",
            "wednesday_close": "22:00",
            "thursday_open": "18:00",
            "thursday_close": "22:00",
            "friday_open": "18:00",
            "friday_close": "22:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://erasmuspadel.nl",
        "google_maps_link": "https://maps.google.com/?q=Erasmus+Padel+Association+Rotterdam"
    },
    {
        "id": 56,
        "name": "Erasmus Dance Society",
        "type": "Sports Association",
        "latitude": 51.9175,
        "longitude": 4.5250,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        "tags": ["dance", "students", "performance", "training", "social"],
        "languages": ["NL", "EN"],
        "description": "Erasmus Dance Society offers students a chance to participate in dance workshops, courses, and performances across a range of styles.",
        "opening_times": {
            "monday_open": "17:00",
            "monday_close": "21:00",
            "tuesday_open": "17:00",
            "tuesday_close": "21:00",
            "wednesday_open": "17:00",
            "wednesday_close": "21:00",
            "thursday_open": "17:00",
            "thursday_close": "21:00",
            "friday_open": "17:00",
            "friday_close": "21:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://www.erasmusdancesociety.nl",
        "google_maps_link": "https://maps.google.com/?q=Erasmus+Dance+Society+Rotterdam"
    },
    {
        "id": 57,
        "name": "EUR-Roadrunners",
        "type": "Sports Association",
        "latitude": 51.9175,
        "longitude": 4.5250,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        "tags": ["running", "athletics", "students", "endurance", "training", "social"],
        "languages": ["NL", "EN"],
        "description": "The EUR-Roadrunners is the student running club of Erasmus University Rotterdam, offering weekly training and participation in events.",
        "opening_times": {
            "monday_open": "18:00",
            "monday_close": "20:00",
            "tuesday_open": "Closed",
            "tuesday_close": "Closed",
            "wednesday_open": "18:00",
            "wednesday_close": "20:00",
            "thursday_open": "Closed",
            "thursday_close": "Closed",
            "friday_open": "Closed",
            "friday_close": "Closed",
            "saturday_open": "10:00",
            "saturday_close": "12:00",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://eurroadrunners.nl",
        "google_maps_link": "https://maps.google.com/?q=EUR-Roadrunners+Rotterdam"
    },
    {
        "id": 58,
        "name": "R.S.R.C. (Rotterdamse Studenten Rugby Club)",
        "type": "Sports Association",
        "latitude": 51.9165,
        "longitude": 4.5253,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Woudestein, Kralingse Zoom 91, 3063 ND Rotterdam",
        "tags": ["rugby", "team sports", "students", "competition", "social", "training"],
        "languages": ["NL", "EN"],
        "description": "R.S.R.C. is the official rugby club for students in Rotterdam, known for its competitive spirit and vibrant club culture.",
        "opening_times": {
            "monday_open": "18:30",
            "monday_close": "21:00",
            "tuesday_open": "Closed",
            "tuesday_close": "Closed",
            "wednesday_open": "18:30",
            "wednesday_close": "21:00",
            "thursday_open": "Closed",
            "thursday_close": "Closed",
            "friday_open": "Closed",
            "friday_close": "Closed",
            "saturday_open": "13:00",
            "saturday_close": "18:00",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://www.rsrc.nl",
        "google_maps_link": "https://maps.google.com/?q=R.S.R.C.+Rotterdam"
    },
    {
        "id": 59,
        "name": "RSM STAR",
        "type": "Study Association",
        "latitude": 51.9175,
        "longitude": 4.5250,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        "tags": ["study association", "students", "business", "networking", "events", "education", "academic", "community", "leadership", "career development"],
        "languages": ["NL", "EN"],
        "description": "RSM STAR is the study association of Rotterdam School of Management, Erasmus University, and is Europe's largest student-ruled study association.",
        "opening_times": {
            "monday_open": "09:00",
            "monday_close": "17:00",
            "tuesday_open": "09:00",
            "tuesday_close": "17:00",
            "wednesday_open": "09:00",
            "wednesday_close": "17:00",
            "thursday_open": "09:00",
            "thursday_close": "17:00",
            "friday_open": "09:00",
            "friday_close": "17:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://rsmstar.nl/",
        "google_maps_link": "https://maps.google.com/?q=RSM+STAR+Rotterdam"
    },
    {
        "id": 60,
        "name": "Café In de Smitse",
        "type": "Campus Bar",
        "latitude": 51.9175,
        "longitude": 4.5250,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
        "tags": ["campus bar", "students", "beer", "social", "affordable", "casual", "music", "community", "university", "relaxing"],
        "languages": ["NL", "EN"],
        "description": "Café In de Smitse is the campus bar of Erasmus University Rotterdam, offering a personal touch to meet friends, fellow students, and colleagues after a hard day's work.",
        "opening_times": {
            "monday_open": "16:00",
            "monday_close": "23:00",
            "tuesday_open": "16:00",
            "tuesday_close": "23:00",
            "wednesday_open": "16:00",
            "wednesday_close": "23:00",
            "thursday_open": "16:00",
            "thursday_close": "23:00",
            "friday_open": "16:00",
            "friday_close": "23:00",
            "saturday_open": "Closed",
            "saturday_close": "Closed",
            "sunday_open": "Closed",
            "sunday_close": "Closed"
        },
        "logo": null,
        "website": "https://www.indesmitse.nl/",
        "google_maps_link": "https://maps.google.com/?q=Café+In+de+Smitse+Rotterdam"
    },
    {
        "id": 61,
        "name": "Eetcafé Concordia",
        "type": "Student Bar",
        "latitude": 51.9220,
        "longitude": 4.5300,
        "city": "Rotterdam",
        "district": "Kralingen-Crooswijk",
        "address": "Oostzeedijk 56a, 3063 BD Rotterdam",
        "tags": ["student bar", "affordable", "social", "pub quizzes", "beer pong", "casual", "community", "entertainment", "students", "events"],
        "languages": ["NL", "EN"],
        "description": "Eetcafé Concordia is a popular student bar near Erasmus University, offering affordable drinks, pub quizzes, and a vibrant atmosphere for students.",
        "opening_times": {
            "monday_open": "16:00",
            "monday_close": "01:00",
            "tuesday_open": "16:00",
            "tuesday_close": "01:00",
            "wednesday_open": "16:00",
            "wednesday_close": "01:00",
            "thursday_open": "16:00",
            "thursday_close": "01:00",
            "friday_open": "16:00",
            "friday_close": "02:00",
            "saturday_open": "16:00",
            "saturday_close": "02:00",
            "sunday_open": "16:00",
            "sunday_close": "01:00"
        },
        "logo": null,
        "website": "https://eetcafeconcordia.com/",
        "google_maps_link": "https://maps.google.com/?q=Eetcafé+Concordia+Rotterdam"
    },
    {
        "id": 62,
        "name": "Jazzcafé Dizzy",
        "type": "Café/Live Music Venue",
        "latitude": 51.9160,
        "longitude": 4.4630,
        "city": "Rotterdam",
        "district": "Delfshaven",
        "address": "'s-Gravendijkwal 127, 3021 EK Rotterdam",
        "tags": ["jazz", "live music", "café", "bar", "culture", "entertainment", "historic", "community", "events", "art"],
        "languages": ["NL", "EN"],
        "description": "Jazzcafé Dizzy is a renowned jazz café in Rotterdam, offering live music performances in a cozy and intimate setting since 1977.",
        "opening_times": {
            "monday_open": "16:00",
            "monday_close": "02:00",
            "tuesday_open": "16:00",
            "tuesday_close": "02:00",
            "wednesday_open": "16:00",
            "wednesday_close": "02:00",
            "thursday_open": "16:00",
            "thursday_close": "02:00",
            "friday_open": "16:00",
            "friday_close": "02:00",
            "saturday_open": "16:00",
            "saturday_close": "02:00",
            "sunday_open": "16:00",
            "sunday_close": "02:00"
        },
        "logo": null,
        "website": "https://dizzy.nl/",
        "google_maps_link": "https://maps.google.com/?q=Jazzcafé+Dizzy+Rotterdam"
    },
    {
        "id": 63,
        "name": "De Witte Aap",
        "type": "Bar",
        "latitude": 51.9140,
        "longitude": 4.4770,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Witte de Withstraat 78, 3012 BS Rotterdam",
        "tags": ["bar", "nightlife", "social", "historic", "culture", "art district", "beer", "casual", "community", "entertainment"],
        "languages": ["NL", "EN"],
        "description": "De Witte Aap is a vibrant bar located in Rotterdam's art district, known for its lively atmosphere and diverse crowd.",
        "opening_times": {
            "monday_open": "15:00",
            "monday_close": "02:00",
            "tuesday_open": "15:00",
            "tuesday_close": "02:00",
            "wednesday_open": "15:00",
            "wednesday_close": "02:00",
            "thursday_open": "15:00",
            "thursday_close": "02:00",
            "friday_open": "15:00",
            "friday_close": "04:00",
            "saturday_open": "15:00",
            "saturday_close": "04:00",
            "sunday_open": "15:00",
            "sunday_close": "02:00"
        },
        "logo": null,
        "website": "https://www.dewitteaap.nl/",
        "google_maps_link": "https://maps.google.com/?q=De+Witte+Aap+Rotterdam"
    },
    {
        "id": 64,
        "name": "Bagels & Beans",
        "type": "Café",
        "latitude": 51.9170,
        "longitude": 4.4860,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Stieltjesstraat 210, 3071 JX Rotterdam",
        "tags": ["café", "bagels", "coffee", "breakfast", "lunch", "casual", "healthy", "vegetarian", "relaxing", "community"],
        "languages": ["NL", "EN"],
        "description": "Bagels & Beans is a cozy café offering a variety of bagels, coffee, and healthy options in a relaxed atmosphere.",
        "opening_times": {
            "monday_open": "08:30",
            "monday_close": "17:00",
            "tuesday_open": "08:30",
            "tuesday_close": "17:00",
            "wednesday_open": "08:30",
            "wednesday_close": "17:00",
            "thursday_open": "08:30",
            "thursday_close": "17:00",
            "friday_open": "08:30",
            "friday_close": "17:00",
            "saturday_open": "10:00",
            "saturday_close": "17:00",
            "sunday_open": "10:00",
            "sunday_close": "17:00"
        },
        "logo": null,
        "website": "https://maps.google.com/?q=Bagels+Beans+Rotterdam",
        "google_maps_link": "https://maps.google.com/?q=Bagels+Beans+Rotterdam"
    },
    {
        "id": 65,
        "name": "Coffee Company",
        "type": "Café",
        "latitude": 51.9175,
        "longitude": 4.4765,
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "address": "Eendrachtsplein 2, 3012 LA Rotterdam",
        "tags": ["café", "coffee", "study spot", "laptop-friendly", "casual", "social", "drinks", "public", "relaxing", "work-friendly"],
        "languages": ["NL", "EN"],
        "description": "Coffee Company is a popular café chain in the Netherlands, offering a variety of coffee drinks and a comfortable environment for both socializing and working.",
        "opening_times": {
            "monday_open": "07:30",
            "monday_close": "19:00",
            "tuesday_open": "07:30",
            "tuesday_close": "19:00",
            "wednesday_open": "07:30",
            "wednesday_close": "19:00",
            "thursday_open": "07:30",
            "thursday_close": "19:00",
            "friday_open": "07:30",
            "friday_close": "19:00",
            "saturday_open": "08:30",
            "saturday_close": "19:00",
            "sunday_open": "08:30",
            "sunday_close": "19:00"
        },
        "logo": null,
        "website": "https://coffeecompany.nl/locations/eendrachtsplein-2/",
        "google_maps_link": "https://maps.google.com/?q=Coffee+Company+Eendrachtsplein+Rotterdam"
    }
];