export const PLACES_DEMO = [
    {
        "id": 0,
        "name": "Donner",
        "type": "Bookstore",
        "languages": [ "EN", "NL", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "10:00",
    },
    {
        "id": 1,
        "name": "Erasmus Esports",
        "type": "Student Sport Association",
        "languages": ["EN", "NL", "Other"],
        "city": "Rotterdam",
        "district": "Feijenoord",
        "next_opening_time": "Wednesday 19:00",
    },
    {
        "id": 2,
        "name": "Skateland",
        "type": "Sports",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Feijenoord",
        "next_opening_time": "00:00",
    },
    {
        "id": 3,
        "name": "Rotown",
        "type": "Concert Venue / Music Bar",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 4,
        "name": "Bar3",
        "type": "Music Bar",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 5,
        "name": "160K",
        "type": "Arcade Hall / Bar",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 6,
        "name": "Kino",
        "type": "Cinema",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 7,
        "name": "Worm",
        "type": "Art Center",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 8,
        "name": "V2",
        "type": "Art Center",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 9,
        "name": "Szeneviertel",
        "type": "Bar",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 10,
        "name": "Wunderbar",
        "type": "Bar",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 8,
        "name": "V2",
        "type": "Art Center",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
    {
        "id": 9,
        "name": "Szeneviertel",
        "type": "Bar",
        "languages": [ "NL", "EN", "Other"],
        "city": "Rotterdam",
        "district": "Stadscentrum",
        "next_opening_time": "00:00",
    },
]