export const PLACES_DEMO = [
  {
    id: 0,
    name: "Donner",
    type: "Bookstore",
    latitude: 51.918852498892,
    longitude: 4.479435816744115,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Coolsingel 119, 3012 AG Rotterdam",
    tags: ["books", "culture", "reading"],
    languages: ["EN", "NL", "Other"],
    description: "Donner is one of the largest bookstores in the Netherlands, offering a wide range of books in multiple languages and hosting regular cultural events.",
    opening_times: {
      monday_open: "09:00",
      monday_close: "18:00",
      tuesday_open: "09:00",
      tuesday_close: "18:00",
      wednesday_open: "09:00",
      wednesday_close: "18:00",
      thursday_open: "09:00",
      thursday_close: "21:00",
      friday_open: "09:00",
      friday_close: "18:00",
      saturday_open: "09:00",
      saturday_close: "17:00",
      sunday_open: "12:00",
      sunday_close: "17:00"
    },
    logo: require("@/assets/images/placesdemo/donner-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=Donner+Rotterdam"
  },
  {
    id: 1,
    name: "Erasmus Esports",
    type: "Student Sport Association",
    latitude: 51.91008440463913,
    longitude: 4.509421634628058,
    city: "Rotterdam",
    district: "Feijenoord",
    address: "Burgemeester Oudlaan 50, 3062 PA Rotterdam",
    tags: ["gaming", "student", "community"],
    languages: ["EN", "NL", "Other"],
    description: "Erasmus Esports is a student-run organization at Erasmus University Rotterdam, offering a community for gamers to connect, compete, and collaborate through various events and tournaments.",
    opening_times: {
      monday_open: null,
      monday_close: null,
      tuesday_open: "19:00",
      tuesday_close: "23:00",
      wednesday_open: "19:00",
      wednesday_close: "23:00",
      thursday_open: null,
      thursday_close: null,
      friday_open: "19:00",
      friday_close: "23:00",
      saturday_open: null,
      saturday_close: null,
      sunday_open: null,
      sunday_close: null
    },
    logo: require("@/assets/images/placesdemo/erasmusesports-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=Erasmus+Esports+Rotterdam"
  },
  {
    id: 2,
    name: "Skateland",
    type: "Sports",
    latitude: 51.90793221738516,
    longitude: 4.5120429426214494,
    city: "Rotterdam",
    district: "Feijenoord",
    address: "Piekstraat 45, 3071 EL Rotterdam",
    tags: ["skateboarding", "BMX", "indoor park"],
    languages: ["NL", "EN", "Other"],
    description: "Skateland is one of the largest indoor skateparks in the Netherlands, offering facilities for skateboarding, BMX, and inline skating, along with lessons and events for all ages.",
    opening_times: {
      monday_open: null,
      monday_close: null,
      tuesday_open: null,
      tuesday_close: null,
      wednesday_open: "15:00",
      wednesday_close: "22:00",
      thursday_open: "15:00",
      thursday_close: "22:00",
      friday_open: "15:00",
      friday_close: "22:00",
      saturday_open: "13:00",
      saturday_close: "18:00",
      sunday_open: "13:00",
      sunday_close: "18:00"
    },
    logo: require("@/assets/images/placesdemo/skateland-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=Skateland+Rotterdam"
  },
  {
    id: 3,
    name: "Rotown",
    type: "Concert Venue / Music Bar",
    latitude: 51.91689793565822,
    longitude: 4.471683329939567,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Nieuwe Binnenweg 19, 3014 GB Rotterdam",
    tags: ["live music", "bar", "restaurant"],
    languages: ["NL", "EN", "Other"],
    description: "Rotown is a renowned music venue and café in Rotterdam, hosting a variety of live performances ranging from indie bands to international artists, complemented by a cozy bar and restaurant.",
    opening_times: {
      monday_open: "12:00",
      monday_close: "04:00",
      tuesday_open: "12:00",
      tuesday_close: "04:00",
      wednesday_open: "12:00",
      wednesday_close: "04:00",
      thursday_open: "12:00",
      thursday_close: "04:00",
      friday_open: "11:00",
      friday_close: "04:00",
      saturday_open: "11:00",
      saturday_close: "04:00",
      sunday_open: "11:00",
      sunday_close: "04:00"
    },
    logo: require("@/assets/images/placesdemo/rotown-favicon.jpg"),
    google_maps_link: "https://maps.google.com/?q=Rotown+Rotterdam"
  },
  {
    id: 4,
    name: "Bar3",
    type: "Music Bar",
    latitude: 51.92045667961497,
    longitude: 4.4755949619232185,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Nieuwe Binnenweg 17, 3014 GB Rotterdam",
    tags: ["alternative", "music", "bar"],
    languages: ["NL", "EN", "Other"],
    description: "Bar3 is an alternative music bar in Rotterdam, known for its eclectic music selection, vibrant atmosphere, and a variety of live performances and DJ sets.",
    opening_times: {
      monday_open: "19:00",
      monday_close: "03:00",
      tuesday_open: "19:00",
      tuesday_close: "03:00",
      wednesday_open: "19:00",
      wednesday_close: "03:00",
      thursday_open: "19:00",
      thursday_close: "03:00",
      friday_open: "19:00",
      friday_close: "04:00",
      saturday_open: "19:00",
      saturday_close: "04:00",
      sunday_open: "19:00",
      sunday_close: "03:00"
    },
    logo: require("@/assets/images/placesdemo/bar3-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=Bar3+Rotterdam"
  },
  {
    id: 5,
    name: "160K",
    type: "Arcade Hall / Bar",
    latitude: 51.92045667961497,
    longitude: 4.4755949619232185,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Schiekade 201, 3013 BR Rotterdam",
    tags: ["arcade", "retro games", "bar"],
    languages: ["NL", "EN", "Other"],
    description: "160K is a retro arcade hall and bar in Rotterdam, offering a nostalgic gaming experience with classic arcade machines, complemented by a selection of drinks and snacks.",
    opening_times: {
      monday_open: null,
      monday_close: null,
      tuesday_open: null,
      tuesday_close: null,
      wednesday_open: "17:00",
      wednesday_close: "00:00",
      thursday_open: "17:00",
      thursday_close: "01:00",
      friday_open: "17:00",
      friday_close: "02:00",
      saturday_open: "16:00",
      saturday_close: "02:00",
      sunday_open: null,
      sunday_close: null
    },
    logo: require("@/assets/images/placesdemo/160k-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=160K+Rotterdam"
  },
    {
    id: 6,
    name: "Kino",
    type: "Cinema",
    latitude: 51.92045667961497,
    longitude: 4.4755949619232185,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Gouvernestraat 129-133, 3014 PM Rotterdam",
    tags: ["cinema", "film", "culture"],
    languages: ["NL", "EN", "Other"],
    description: "Kino is a cinema, restaurant, and creative workspace in the heart of Rotterdam, offering a diverse range of films from arthouse to blockbusters.",
    opening_times: {
      monday_open: "10:00",
      monday_close: "01:00",
      tuesday_open: "10:00",
      tuesday_close: "01:00",
      wednesday_open: "10:00",
      wednesday_close: "01:00",
      thursday_open: "10:00",
      thursday_close: "01:00",
      friday_open: "10:00",
      friday_close: "02:00",
      saturday_open: "10:00",
      saturday_close: "02:00",
      sunday_open: "10:00",
      sunday_close: "01:00"
    },
    logo: require("@/assets/images/placesdemo/kino-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=Kino+Rotterdam"
  },
  {
    id: 7,
    name: "Worm",
    type: "Art Center",
    latitude: 51.92045667961497,
    longitude: 4.4755949619232185,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Boomgaardsstraat 71, 3012 XA Rotterdam",
    tags: ["art", "culture", "music"],
    languages: ["NL", "EN", "Other"],
    description: "WORM is a multidisciplinary cultural center in Rotterdam, hosting concerts, film screenings, exhibitions, and more.",
    opening_times: {
      monday_open: "12:00",
      monday_close: "01:00",
      tuesday_open: "12:00",
      tuesday_close: "01:00",
      wednesday_open: "12:00",
      wednesday_close: "01:00",
      thursday_open: "12:00",
      thursday_close: "01:00",
      friday_open: "12:00",
      friday_close: "02:00",
      saturday_open: "12:00",
      saturday_close: "02:00",
      sunday_open: "12:00",
      sunday_close: "01:00"
    },
    logo: require("@/assets/images/placesdemo/worm-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=WORM+Rotterdam"
  },
  {
    id: 8,
    name: "V2",
    type: "Art Center",
    latitude: 51.92045667961497,
    longitude: 4.4755949619232185,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Eendrachtsstraat 10, 3012 XL Rotterdam",
    tags: ["art", "technology", "media"],
    languages: ["NL", "EN", "Other"],
    description: "V2_ is an interdisciplinary center for art and media technology, organizing exhibitions, presentations, and research projects.",
    opening_times: {
      monday_open: "10:00",
      monday_close: "18:00",
      tuesday_open: "10:00",
      tuesday_close: "18:00",
      wednesday_open: "10:00",
      wednesday_close: "18:00",
      thursday_open: "10:00",
      thursday_close: "18:00",
      friday_open: "10:00",
      friday_close: "18:00",
      saturday_open: "Closed",
      saturday_close: "Closed",
      sunday_open: "Closed",
      sunday_close: "Closed"
    },
    logo: require("@/assets/images/placesdemo/v2-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=V2+Rotterdam"
  },
  {
    id: 9,
    name: "Szeneviertel",
    type: "Bar",
    latitude: 51.92045667961497,
    longitude: 4.4755949619232185,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Witte de Withstraat 63, 3012 BN Rotterdam",
    tags: ["bar", "drinks", "music"],
    languages: ["NL", "EN", "Other"],
    description: "Szeneviertel is a trendy bar located in the vibrant Witte de Withstraat, known for its eclectic music and lively atmosphere.",
    opening_times: {
      monday_open: "16:00",
      monday_close: "01:00",
      tuesday_open: "16:00",
      tuesday_close: "01:00",
      wednesday_open: "16:00",
      wednesday_close: "01:00",
      thursday_open: "16:00",
      thursday_close: "01:00",
      friday_open: "16:00",
      friday_close: "02:00",
      saturday_open: "16:00",
      saturday_close: "02:00",
      sunday_open: "16:00",
      sunday_close: "01:00"
    },
    logo: require("@/assets/images/placesdemo/szeneviertel-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=Szeneviertel+Rotterdam"
  },
  {
    id: 10,
    name: "Wunderbar",
    type: "Bar",
    latitude: 51.92045667961497,
    longitude: 4.4755949619232185,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Boomgaardsstraat 71, 3012 XA Rotterdam",
    tags: ["bar", "alternative", "culture"],
    languages: ["NL", "EN", "Other"],
    description: "Wunderbar is an alternative bar located within WORM, offering a unique selection of drinks and a cozy atmosphere.",
    opening_times: {
      monday_open: "12:00",
      monday_close: "01:00",
      tuesday_open: "12:00",
      tuesday_close: "01:00",
      wednesday_open: "12:00",
      wednesday_close: "01:00",
      thursday_open: "12:00",
      thursday_close: "01:00",
      friday_open: "12:00",
      friday_close: "02:00",
      saturday_open: "12:00",
      saturday_close: "02:00",
      sunday_open: "12:00",
      sunday_close: "01:00"
    },
    logo: require("@/assets/images/placesdemo/v2-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=Wunderbar+Rotterdam"
  },
  {
    id: 11,
    name: "Hogeschool Rotterdam",
    type: "School",
    latitude: 51.91731349749627,
    longitude: 4.484378867887312,
    city: "Rotterdam",
    district: "Stadscentrum",
    address: "Rochussenstraat 198, 3015 EK Rotterdam",
    tags: ["education", "university", "students"],
    languages: ["NL", "EN", "Other"],
    description: "Hogeschool Rotterdam is a university of applied sciences offering a wide range of bachelor's and master's programs.",
    opening_times: {
      monday_open: "07:30",
      monday_close: "19:00",
      tuesday_open: "07:30",
      tuesday_close: "20:00",
      wednesday_open: "07:30",
      wednesday_close: "19:00",
      thursday_open: "07:30",
      thursday_close: "19:00",
      friday_open: "07:30",
      friday_close: "18:00",
      saturday_open: "Closed",
      saturday_close: "Closed",
      sunday_open: "Closed",
      sunday_close: "Closed"
    },
    logo: require("@/assets/images/placesdemo/v2-favicon.png"),
    google_maps_link: "https://maps.google.com/?q=Hogeschool+Rotterdam"
  }
];